// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use crate::api::kafka_utils::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 839132467;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__kafka_analyzer__analyze_topic_content_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_topic_content",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            let api_topic = <String>::sse_decode(&mut deserializer);
            let api_max_messages = <Option<i64>>::sse_decode(&mut deserializer);
            let api_sample_from_latest = <bool>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::kafka_types::TopicAnalysisProgress,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::kafka_analyzer::analyze_topic_content(
                            api_profile,
                            api_topic,
                            api_max_messages,
                            api_sample_from_latest,
                            api_sink,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__kafka_consumer__consume_with_filter_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "consume_with_filter",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            let api_topic = <String>::sse_decode(&mut deserializer);
            let api_filter_terms = <Option<Vec<String>>>::sse_decode(&mut deserializer);
            let api_filter_field = <Option<String>>::sse_decode(&mut deserializer);
            let api_filter_type =
                <crate::api::kafka_types::FilterType>::sse_decode(&mut deserializer);
            let api_search_scope =
                <crate::api::kafka_types::SearchScope>::sse_decode(&mut deserializer);
            let api_start_offset = <Option<i64>>::sse_decode(&mut deserializer);
            let api_start_timestamp = <Option<i64>>::sse_decode(&mut deserializer);
            let api_start_partition = <Option<i32>>::sse_decode(&mut deserializer);
            let api_fast_trace_key = <Option<String>>::sse_decode(&mut deserializer);
            let api_end_offset = <Option<i64>>::sse_decode(&mut deserializer);
            let api_end_timestamp = <Option<i64>>::sse_decode(&mut deserializer);
            let api_max_results = <Option<i32>>::sse_decode(&mut deserializer);
            let api_run_forever = <bool>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::kafka_consumer::KafkaMessage,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::kafka_consumer::consume_with_filter(
                            api_profile,
                            api_topic,
                            api_filter_terms,
                            api_filter_field,
                            api_filter_type,
                            api_search_scope,
                            api_start_offset,
                            api_start_timestamp,
                            api_start_partition,
                            api_fast_trace_key,
                            api_end_offset,
                            api_end_timestamp,
                            api_max_results,
                            api_run_forever,
                            api_sink,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__kafka_utils__create_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::kafka_utils::create_config(&api_profile))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__kafka_metadata__fetch_consumer_group_lag_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_consumer_group_lag",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            let api_group_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::kafka_metadata::fetch_consumer_group_lag(
                            api_profile,
                            api_group_id,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__kafka_metadata__fetch_consumer_groups_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_consumer_groups",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::kafka_metadata::fetch_consumer_groups(api_profile)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__kafka_metadata__fetch_consumer_lags_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_consumer_lags",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::kafka_metadata::fetch_consumer_lags(api_profile)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__schema_registry__fetch_schema_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_schema",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            let api_subject = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::schema_registry::fetch_schema(api_profile, api_subject)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__schema_registry__fetch_subjects_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_subjects",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::schema_registry::fetch_subjects(api_profile)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__kafka_metadata__fetch_topics_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_topics",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::kafka_metadata::fetch_topics(api_profile)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__kafka_utils__murmur2_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "murmur2",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::kafka_utils::murmur2(&api_data))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__kafka_utils__to_positive_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "to_positive",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_number = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::kafka_utils::to_positive(api_number))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__kafka_metadata__validate_connection_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_connection",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile =
                <crate::api::kafka_types::ClusterProfile>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::kafka_metadata::validate_connection(api_profile)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>
);

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for ClientConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::kafka_consumer::KafkaMessage,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::kafka_types::TopicAnalysisProgress,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::kafka_types::ClusterProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_bootstrapServers = <String>::sse_decode(deserializer);
        let mut var_saslUsername = <Option<String>>::sse_decode(deserializer);
        let mut var_saslPassword = <Option<String>>::sse_decode(deserializer);
        let mut var_mechanism = <Option<String>>::sse_decode(deserializer);
        let mut var_securityProtocol = <Option<String>>::sse_decode(deserializer);
        let mut var_schemaRegistryUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_sslKeystoreLocation = <Option<String>>::sse_decode(deserializer);
        let mut var_sslKeystorePassword = <Option<String>>::sse_decode(deserializer);
        let mut var_sslTruststoreLocation = <Option<String>>::sse_decode(deserializer);
        let mut var_sslTruststorePassword = <Option<String>>::sse_decode(deserializer);
        let mut var_schemaRegistryUsername = <Option<String>>::sse_decode(deserializer);
        let mut var_schemaRegistryPassword = <Option<String>>::sse_decode(deserializer);
        let mut var_saslKerberosServiceName = <Option<String>>::sse_decode(deserializer);
        let mut var_saslKerberosKeytab = <Option<String>>::sse_decode(deserializer);
        let mut var_saslKerberosPrincipal = <Option<String>>::sse_decode(deserializer);
        let mut var_saslKerberosConf = <Option<String>>::sse_decode(deserializer);
        let mut var_saslOauthbearerToken = <Option<String>>::sse_decode(deserializer);
        let mut var_sslPemCertificateLocation = <Option<String>>::sse_decode(deserializer);
        let mut var_sslPemKeyLocation = <Option<String>>::sse_decode(deserializer);
        let mut var_sslPemKeyPassword = <Option<String>>::sse_decode(deserializer);
        return crate::api::kafka_types::ClusterProfile {
            name: var_name,
            bootstrap_servers: var_bootstrapServers,
            sasl_username: var_saslUsername,
            sasl_password: var_saslPassword,
            mechanism: var_mechanism,
            security_protocol: var_securityProtocol,
            schema_registry_url: var_schemaRegistryUrl,
            ssl_keystore_location: var_sslKeystoreLocation,
            ssl_keystore_password: var_sslKeystorePassword,
            ssl_truststore_location: var_sslTruststoreLocation,
            ssl_truststore_password: var_sslTruststorePassword,
            schema_registry_username: var_schemaRegistryUsername,
            schema_registry_password: var_schemaRegistryPassword,
            sasl_kerberos_service_name: var_saslKerberosServiceName,
            sasl_kerberos_keytab: var_saslKerberosKeytab,
            sasl_kerberos_principal: var_saslKerberosPrincipal,
            sasl_kerberos_conf: var_saslKerberosConf,
            sasl_oauthbearer_token: var_saslOauthbearerToken,
            ssl_pem_certificate_location: var_sslPemCertificateLocation,
            ssl_pem_key_location: var_sslPemKeyLocation,
            ssl_pem_key_password: var_sslPemKeyPassword,
        };
    }
}

impl SseDecode for crate::api::kafka_types::ConsumerGroupLag {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_groupId = <String>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_protocolType = <String>::sse_decode(deserializer);
        let mut var_partitionLags =
            <Vec<crate::api::kafka_types::TopicPartitionLag>>::sse_decode(deserializer);
        let mut var_membersCount = <i32>::sse_decode(deserializer);
        let mut var_topicsCount = <i32>::sse_decode(deserializer);
        return crate::api::kafka_types::ConsumerGroupLag {
            group_id: var_groupId,
            state: var_state,
            protocol_type: var_protocolType,
            partition_lags: var_partitionLags,
            members_count: var_membersCount,
            topics_count: var_topicsCount,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::kafka_types::FieldOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_fieldName = <String>::sse_decode(deserializer);
        let mut var_count = <i64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        let mut var_topValues =
            <Vec<crate::api::kafka_types::FieldValueOccurrence>>::sse_decode(deserializer);
        return crate::api::kafka_types::FieldOccurrence {
            field_name: var_fieldName,
            count: var_count,
            percentage: var_percentage,
            top_values: var_topValues,
        };
    }
}

impl SseDecode for crate::api::kafka_types::FieldValueOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_value = <String>::sse_decode(deserializer);
        let mut var_count = <i64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        return crate::api::kafka_types::FieldValueOccurrence {
            value: var_value,
            count: var_count,
            percentage: var_percentage,
        };
    }
}

impl SseDecode for crate::api::kafka_types::FilterType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::kafka_types::FilterType::Contains,
            1 => crate::api::kafka_types::FilterType::Regex,
            2 => crate::api::kafka_types::FilterType::Exact,
            _ => unreachable!("Invalid variant for FilterType: {}", inner),
        };
    }
}

impl SseDecode for crate::api::kafka_types::HourlyCount {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hour = <i32>::sse_decode(deserializer);
        let mut var_count = <i64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        return crate::api::kafka_types::HourlyCount {
            hour: var_hour,
            count: var_count,
            percentage: var_percentage,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::kafka_consumer::KafkaHeader {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        return crate::api::kafka_consumer::KafkaHeader {
            key: var_key,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::kafka_consumer::KafkaMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_topic = <String>::sse_decode(deserializer);
        let mut var_partition = <i32>::sse_decode(deserializer);
        let mut var_offset = <i64>::sse_decode(deserializer);
        let mut var_key = <Option<String>>::sse_decode(deserializer);
        let mut var_payload = <Option<String>>::sse_decode(deserializer);
        let mut var_timestamp = <i64>::sse_decode(deserializer);
        let mut var_headers =
            <Option<Vec<crate::api::kafka_consumer::KafkaHeader>>>::sse_decode(deserializer);
        return crate::api::kafka_consumer::KafkaMessage {
            topic: var_topic,
            partition: var_partition,
            offset: var_offset,
            key: var_key,
            payload: var_payload,
            timestamp: var_timestamp,
            headers: var_headers,
        };
    }
}

impl SseDecode for crate::api::kafka_types::KeyOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_count = <i64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        return crate::api::kafka_types::KeyOccurrence {
            key: var_key,
            count: var_count,
            percentage: var_percentage,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::ConsumerGroupLag> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::ConsumerGroupLag>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::FieldOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::FieldOccurrence>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::FieldValueOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::FieldValueOccurrence>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::HourlyCount> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::HourlyCount>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_consumer::KafkaHeader> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_consumer::KafkaHeader>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::KeyOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::KeyOccurrence>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::PartitionAnalysis> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::PartitionAnalysis>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_metadata::TopicMetadata> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_metadata::TopicMetadata>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::TopicPartitionLag> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::TopicPartitionLag>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::kafka_types::TypeOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::kafka_types::TypeOccurrence>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::kafka_types::TopicAnalysisReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::kafka_types::TopicAnalysisReport>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<String>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<crate::api::kafka_consumer::KafkaHeader>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<crate::api::kafka_consumer::KafkaHeader>>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::kafka_types::PartitionAnalysis {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_partition = <i32>::sse_decode(deserializer);
        let mut var_messageCount = <i64>::sse_decode(deserializer);
        let mut var_byteSize = <i64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        let mut var_earliestOffset = <i64>::sse_decode(deserializer);
        let mut var_latestOffset = <i64>::sse_decode(deserializer);
        return crate::api::kafka_types::PartitionAnalysis {
            partition: var_partition,
            message_count: var_messageCount,
            byte_size: var_byteSize,
            percentage: var_percentage,
            earliest_offset: var_earliestOffset,
            latest_offset: var_latestOffset,
        };
    }
}

impl SseDecode for crate::api::kafka_types::SearchScope {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::kafka_types::SearchScope::Key,
            1 => crate::api::kafka_types::SearchScope::Value,
            2 => crate::api::kafka_types::SearchScope::Both,
            _ => unreachable!("Invalid variant for SearchScope: {}", inner),
        };
    }
}

impl SseDecode for crate::api::kafka_types::TopicAnalysisProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_scannedMessages = <i64>::sse_decode(deserializer);
        let mut var_totalMessagesToScan = <i64>::sse_decode(deserializer);
        let mut var_progress = <f64>::sse_decode(deserializer);
        let mut var_messagesPerSecond = <f64>::sse_decode(deserializer);
        let mut var_currentPartition = <i32>::sse_decode(deserializer);
        let mut var_isComplete = <bool>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        let mut var_partialReport =
            <Option<crate::api::kafka_types::TopicAnalysisReport>>::sse_decode(deserializer);
        return crate::api::kafka_types::TopicAnalysisProgress {
            scanned_messages: var_scannedMessages,
            total_messages_to_scan: var_totalMessagesToScan,
            progress: var_progress,
            messages_per_second: var_messagesPerSecond,
            current_partition: var_currentPartition,
            is_complete: var_isComplete,
            error_message: var_errorMessage,
            partial_report: var_partialReport,
        };
    }
}

impl SseDecode for crate::api::kafka_types::TopicAnalysisReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_topic = <String>::sse_decode(deserializer);
        let mut var_totalMessages = <i64>::sse_decode(deserializer);
        let mut var_totalBytes = <i64>::sse_decode(deserializer);
        let mut var_minMessageSize = <i64>::sse_decode(deserializer);
        let mut var_maxMessageSize = <i64>::sse_decode(deserializer);
        let mut var_avgMessageSize = <f64>::sse_decode(deserializer);
        let mut var_tombstonesCount = <i64>::sse_decode(deserializer);
        let mut var_isCompacted = <bool>::sse_decode(deserializer);
        let mut var_nullKeysCount = <i64>::sse_decode(deserializer);
        let mut var_partitionStats =
            <Vec<crate::api::kafka_types::PartitionAnalysis>>::sse_decode(deserializer);
        let mut var_hourlyDistribution =
            <Vec<crate::api::kafka_types::HourlyCount>>::sse_decode(deserializer);
        let mut var_topKeys =
            <Vec<crate::api::kafka_types::KeyOccurrence>>::sse_decode(deserializer);
        let mut var_contentTypeDistribution =
            <Vec<crate::api::kafka_types::TypeOccurrence>>::sse_decode(deserializer);
        let mut var_fieldFrequencies =
            <Vec<crate::api::kafka_types::FieldOccurrence>>::sse_decode(deserializer);
        let mut var_scanDurationMs = <i64>::sse_decode(deserializer);
        return crate::api::kafka_types::TopicAnalysisReport {
            topic: var_topic,
            total_messages: var_totalMessages,
            total_bytes: var_totalBytes,
            min_message_size: var_minMessageSize,
            max_message_size: var_maxMessageSize,
            avg_message_size: var_avgMessageSize,
            tombstones_count: var_tombstonesCount,
            is_compacted: var_isCompacted,
            null_keys_count: var_nullKeysCount,
            partition_stats: var_partitionStats,
            hourly_distribution: var_hourlyDistribution,
            top_keys: var_topKeys,
            content_type_distribution: var_contentTypeDistribution,
            field_frequencies: var_fieldFrequencies,
            scan_duration_ms: var_scanDurationMs,
        };
    }
}

impl SseDecode for crate::api::kafka_metadata::TopicMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_partitionCount = <i32>::sse_decode(deserializer);
        let mut var_replicationFactor = <i32>::sse_decode(deserializer);
        let mut var_cleanupPolicy = <Option<String>>::sse_decode(deserializer);
        let mut var_retentionMs = <Option<String>>::sse_decode(deserializer);
        return crate::api::kafka_metadata::TopicMetadata {
            name: var_name,
            partition_count: var_partitionCount,
            replication_factor: var_replicationFactor,
            cleanup_policy: var_cleanupPolicy,
            retention_ms: var_retentionMs,
        };
    }
}

impl SseDecode for crate::api::kafka_types::TopicPartitionLag {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_topic = <String>::sse_decode(deserializer);
        let mut var_partition = <i32>::sse_decode(deserializer);
        let mut var_logEndOffset = <i64>::sse_decode(deserializer);
        let mut var_currentOffset = <i64>::sse_decode(deserializer);
        let mut var_lag = <i64>::sse_decode(deserializer);
        return crate::api::kafka_types::TopicPartitionLag {
            topic: var_topic,
            partition: var_partition,
            log_end_offset: var_logEndOffset,
            current_offset: var_currentOffset,
            lag: var_lag,
        };
    }
}

impl SseDecode for crate::api::kafka_types::TypeOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_typeName = <String>::sse_decode(deserializer);
        let mut var_count = <i64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        return crate::api::kafka_types::TypeOccurrence {
            type_name: var_typeName,
            count: var_count,
            percentage: var_percentage,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__kafka_analyzer__analyze_topic_content_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__kafka_consumer__consume_with_filter_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__kafka_utils__create_config_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__kafka_metadata__fetch_consumer_group_lag_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__kafka_metadata__fetch_consumer_groups_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__kafka_metadata__fetch_consumer_lags_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => {
            wire__crate__api__schema_registry__fetch_schema_impl(port, ptr, rust_vec_len, data_len)
        }
        8 => wire__crate__api__schema_registry__fetch_subjects_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__kafka_metadata__fetch_topics_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__init_app_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__kafka_utils__murmur2_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__kafka_utils__to_positive_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__kafka_metadata__validate_connection_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<ClientConfig> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<ClientConfig> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<ClientConfig>> for ClientConfig {
    fn into_into_dart(self) -> FrbWrapper<ClientConfig> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::ClusterProfile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.bootstrap_servers.into_into_dart().into_dart(),
            self.sasl_username.into_into_dart().into_dart(),
            self.sasl_password.into_into_dart().into_dart(),
            self.mechanism.into_into_dart().into_dart(),
            self.security_protocol.into_into_dart().into_dart(),
            self.schema_registry_url.into_into_dart().into_dart(),
            self.ssl_keystore_location.into_into_dart().into_dart(),
            self.ssl_keystore_password.into_into_dart().into_dart(),
            self.ssl_truststore_location.into_into_dart().into_dart(),
            self.ssl_truststore_password.into_into_dart().into_dart(),
            self.schema_registry_username.into_into_dart().into_dart(),
            self.schema_registry_password.into_into_dart().into_dart(),
            self.sasl_kerberos_service_name.into_into_dart().into_dart(),
            self.sasl_kerberos_keytab.into_into_dart().into_dart(),
            self.sasl_kerberos_principal.into_into_dart().into_dart(),
            self.sasl_kerberos_conf.into_into_dart().into_dart(),
            self.sasl_oauthbearer_token.into_into_dart().into_dart(),
            self.ssl_pem_certificate_location
                .into_into_dart()
                .into_dart(),
            self.ssl_pem_key_location.into_into_dart().into_dart(),
            self.ssl_pem_key_password.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::ClusterProfile
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::ClusterProfile>
    for crate::api::kafka_types::ClusterProfile
{
    fn into_into_dart(self) -> crate::api::kafka_types::ClusterProfile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::ConsumerGroupLag {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.group_id.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.protocol_type.into_into_dart().into_dart(),
            self.partition_lags.into_into_dart().into_dart(),
            self.members_count.into_into_dart().into_dart(),
            self.topics_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::ConsumerGroupLag
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::ConsumerGroupLag>
    for crate::api::kafka_types::ConsumerGroupLag
{
    fn into_into_dart(self) -> crate::api::kafka_types::ConsumerGroupLag {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::FieldOccurrence {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.field_name.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
            self.top_values.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::FieldOccurrence
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::FieldOccurrence>
    for crate::api::kafka_types::FieldOccurrence
{
    fn into_into_dart(self) -> crate::api::kafka_types::FieldOccurrence {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::FieldValueOccurrence {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.value.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::FieldValueOccurrence
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::FieldValueOccurrence>
    for crate::api::kafka_types::FieldValueOccurrence
{
    fn into_into_dart(self) -> crate::api::kafka_types::FieldValueOccurrence {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::FilterType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Contains => 0.into_dart(),
            Self::Regex => 1.into_dart(),
            Self::Exact => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::FilterType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::FilterType>
    for crate::api::kafka_types::FilterType
{
    fn into_into_dart(self) -> crate::api::kafka_types::FilterType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::HourlyCount {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.hour.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::HourlyCount
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::HourlyCount>
    for crate::api::kafka_types::HourlyCount
{
    fn into_into_dart(self) -> crate::api::kafka_types::HourlyCount {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_consumer::KafkaHeader {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_consumer::KafkaHeader
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_consumer::KafkaHeader>
    for crate::api::kafka_consumer::KafkaHeader
{
    fn into_into_dart(self) -> crate::api::kafka_consumer::KafkaHeader {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_consumer::KafkaMessage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.topic.into_into_dart().into_dart(),
            self.partition.into_into_dart().into_dart(),
            self.offset.into_into_dart().into_dart(),
            self.key.into_into_dart().into_dart(),
            self.payload.into_into_dart().into_dart(),
            self.timestamp.into_into_dart().into_dart(),
            self.headers.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_consumer::KafkaMessage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_consumer::KafkaMessage>
    for crate::api::kafka_consumer::KafkaMessage
{
    fn into_into_dart(self) -> crate::api::kafka_consumer::KafkaMessage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::KeyOccurrence {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::KeyOccurrence
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::KeyOccurrence>
    for crate::api::kafka_types::KeyOccurrence
{
    fn into_into_dart(self) -> crate::api::kafka_types::KeyOccurrence {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::PartitionAnalysis {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.partition.into_into_dart().into_dart(),
            self.message_count.into_into_dart().into_dart(),
            self.byte_size.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
            self.earliest_offset.into_into_dart().into_dart(),
            self.latest_offset.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::PartitionAnalysis
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::PartitionAnalysis>
    for crate::api::kafka_types::PartitionAnalysis
{
    fn into_into_dart(self) -> crate::api::kafka_types::PartitionAnalysis {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::SearchScope {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Key => 0.into_dart(),
            Self::Value => 1.into_dart(),
            Self::Both => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::SearchScope
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::SearchScope>
    for crate::api::kafka_types::SearchScope
{
    fn into_into_dart(self) -> crate::api::kafka_types::SearchScope {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::TopicAnalysisProgress {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.scanned_messages.into_into_dart().into_dart(),
            self.total_messages_to_scan.into_into_dart().into_dart(),
            self.progress.into_into_dart().into_dart(),
            self.messages_per_second.into_into_dart().into_dart(),
            self.current_partition.into_into_dart().into_dart(),
            self.is_complete.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
            self.partial_report.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::TopicAnalysisProgress
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::TopicAnalysisProgress>
    for crate::api::kafka_types::TopicAnalysisProgress
{
    fn into_into_dart(self) -> crate::api::kafka_types::TopicAnalysisProgress {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::TopicAnalysisReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.topic.into_into_dart().into_dart(),
            self.total_messages.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
            self.min_message_size.into_into_dart().into_dart(),
            self.max_message_size.into_into_dart().into_dart(),
            self.avg_message_size.into_into_dart().into_dart(),
            self.tombstones_count.into_into_dart().into_dart(),
            self.is_compacted.into_into_dart().into_dart(),
            self.null_keys_count.into_into_dart().into_dart(),
            self.partition_stats.into_into_dart().into_dart(),
            self.hourly_distribution.into_into_dart().into_dart(),
            self.top_keys.into_into_dart().into_dart(),
            self.content_type_distribution.into_into_dart().into_dart(),
            self.field_frequencies.into_into_dart().into_dart(),
            self.scan_duration_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::TopicAnalysisReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::TopicAnalysisReport>
    for crate::api::kafka_types::TopicAnalysisReport
{
    fn into_into_dart(self) -> crate::api::kafka_types::TopicAnalysisReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_metadata::TopicMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.partition_count.into_into_dart().into_dart(),
            self.replication_factor.into_into_dart().into_dart(),
            self.cleanup_policy.into_into_dart().into_dart(),
            self.retention_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_metadata::TopicMetadata
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_metadata::TopicMetadata>
    for crate::api::kafka_metadata::TopicMetadata
{
    fn into_into_dart(self) -> crate::api::kafka_metadata::TopicMetadata {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::TopicPartitionLag {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.topic.into_into_dart().into_dart(),
            self.partition.into_into_dart().into_dart(),
            self.log_end_offset.into_into_dart().into_dart(),
            self.current_offset.into_into_dart().into_dart(),
            self.lag.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::TopicPartitionLag
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::TopicPartitionLag>
    for crate::api::kafka_types::TopicPartitionLag
{
    fn into_into_dart(self) -> crate::api::kafka_types::TopicPartitionLag {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::kafka_types::TypeOccurrence {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.type_name.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::kafka_types::TypeOccurrence
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::kafka_types::TypeOccurrence>
    for crate::api::kafka_types::TypeOccurrence
{
    fn into_into_dart(self) -> crate::api::kafka_types::TypeOccurrence {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for ClientConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::kafka_consumer::KafkaMessage,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::kafka_types::TopicAnalysisProgress,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::kafka_types::ClusterProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.bootstrap_servers, serializer);
        <Option<String>>::sse_encode(self.sasl_username, serializer);
        <Option<String>>::sse_encode(self.sasl_password, serializer);
        <Option<String>>::sse_encode(self.mechanism, serializer);
        <Option<String>>::sse_encode(self.security_protocol, serializer);
        <Option<String>>::sse_encode(self.schema_registry_url, serializer);
        <Option<String>>::sse_encode(self.ssl_keystore_location, serializer);
        <Option<String>>::sse_encode(self.ssl_keystore_password, serializer);
        <Option<String>>::sse_encode(self.ssl_truststore_location, serializer);
        <Option<String>>::sse_encode(self.ssl_truststore_password, serializer);
        <Option<String>>::sse_encode(self.schema_registry_username, serializer);
        <Option<String>>::sse_encode(self.schema_registry_password, serializer);
        <Option<String>>::sse_encode(self.sasl_kerberos_service_name, serializer);
        <Option<String>>::sse_encode(self.sasl_kerberos_keytab, serializer);
        <Option<String>>::sse_encode(self.sasl_kerberos_principal, serializer);
        <Option<String>>::sse_encode(self.sasl_kerberos_conf, serializer);
        <Option<String>>::sse_encode(self.sasl_oauthbearer_token, serializer);
        <Option<String>>::sse_encode(self.ssl_pem_certificate_location, serializer);
        <Option<String>>::sse_encode(self.ssl_pem_key_location, serializer);
        <Option<String>>::sse_encode(self.ssl_pem_key_password, serializer);
    }
}

impl SseEncode for crate::api::kafka_types::ConsumerGroupLag {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.group_id, serializer);
        <String>::sse_encode(self.state, serializer);
        <String>::sse_encode(self.protocol_type, serializer);
        <Vec<crate::api::kafka_types::TopicPartitionLag>>::sse_encode(
            self.partition_lags,
            serializer,
        );
        <i32>::sse_encode(self.members_count, serializer);
        <i32>::sse_encode(self.topics_count, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::kafka_types::FieldOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.field_name, serializer);
        <i64>::sse_encode(self.count, serializer);
        <f64>::sse_encode(self.percentage, serializer);
        <Vec<crate::api::kafka_types::FieldValueOccurrence>>::sse_encode(
            self.top_values,
            serializer,
        );
    }
}

impl SseEncode for crate::api::kafka_types::FieldValueOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.value, serializer);
        <i64>::sse_encode(self.count, serializer);
        <f64>::sse_encode(self.percentage, serializer);
    }
}

impl SseEncode for crate::api::kafka_types::FilterType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::kafka_types::FilterType::Contains => 0,
                crate::api::kafka_types::FilterType::Regex => 1,
                crate::api::kafka_types::FilterType::Exact => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::kafka_types::HourlyCount {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.hour, serializer);
        <i64>::sse_encode(self.count, serializer);
        <f64>::sse_encode(self.percentage, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::kafka_consumer::KafkaHeader {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <String>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::kafka_consumer::KafkaMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.topic, serializer);
        <i32>::sse_encode(self.partition, serializer);
        <i64>::sse_encode(self.offset, serializer);
        <Option<String>>::sse_encode(self.key, serializer);
        <Option<String>>::sse_encode(self.payload, serializer);
        <i64>::sse_encode(self.timestamp, serializer);
        <Option<Vec<crate::api::kafka_consumer::KafkaHeader>>>::sse_encode(
            self.headers,
            serializer,
        );
    }
}

impl SseEncode for crate::api::kafka_types::KeyOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <i64>::sse_encode(self.count, serializer);
        <f64>::sse_encode(self.percentage, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::ConsumerGroupLag> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::ConsumerGroupLag>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::FieldOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::FieldOccurrence>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::FieldValueOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::FieldValueOccurrence>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::HourlyCount> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::HourlyCount>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_consumer::KafkaHeader> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_consumer::KafkaHeader>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::KeyOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::KeyOccurrence>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::PartitionAnalysis> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::PartitionAnalysis>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_metadata::TopicMetadata> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_metadata::TopicMetadata>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::TopicPartitionLag> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::TopicPartitionLag>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::kafka_types::TypeOccurrence> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::kafka_types::TypeOccurrence>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::kafka_types::TopicAnalysisReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::kafka_types::TopicAnalysisReport>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<String>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<crate::api::kafka_consumer::KafkaHeader>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<crate::api::kafka_consumer::KafkaHeader>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::kafka_types::PartitionAnalysis {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.partition, serializer);
        <i64>::sse_encode(self.message_count, serializer);
        <i64>::sse_encode(self.byte_size, serializer);
        <f64>::sse_encode(self.percentage, serializer);
        <i64>::sse_encode(self.earliest_offset, serializer);
        <i64>::sse_encode(self.latest_offset, serializer);
    }
}

impl SseEncode for crate::api::kafka_types::SearchScope {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::kafka_types::SearchScope::Key => 0,
                crate::api::kafka_types::SearchScope::Value => 1,
                crate::api::kafka_types::SearchScope::Both => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::kafka_types::TopicAnalysisProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.scanned_messages, serializer);
        <i64>::sse_encode(self.total_messages_to_scan, serializer);
        <f64>::sse_encode(self.progress, serializer);
        <f64>::sse_encode(self.messages_per_second, serializer);
        <i32>::sse_encode(self.current_partition, serializer);
        <bool>::sse_encode(self.is_complete, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
        <Option<crate::api::kafka_types::TopicAnalysisReport>>::sse_encode(
            self.partial_report,
            serializer,
        );
    }
}

impl SseEncode for crate::api::kafka_types::TopicAnalysisReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.topic, serializer);
        <i64>::sse_encode(self.total_messages, serializer);
        <i64>::sse_encode(self.total_bytes, serializer);
        <i64>::sse_encode(self.min_message_size, serializer);
        <i64>::sse_encode(self.max_message_size, serializer);
        <f64>::sse_encode(self.avg_message_size, serializer);
        <i64>::sse_encode(self.tombstones_count, serializer);
        <bool>::sse_encode(self.is_compacted, serializer);
        <i64>::sse_encode(self.null_keys_count, serializer);
        <Vec<crate::api::kafka_types::PartitionAnalysis>>::sse_encode(
            self.partition_stats,
            serializer,
        );
        <Vec<crate::api::kafka_types::HourlyCount>>::sse_encode(
            self.hourly_distribution,
            serializer,
        );
        <Vec<crate::api::kafka_types::KeyOccurrence>>::sse_encode(self.top_keys, serializer);
        <Vec<crate::api::kafka_types::TypeOccurrence>>::sse_encode(
            self.content_type_distribution,
            serializer,
        );
        <Vec<crate::api::kafka_types::FieldOccurrence>>::sse_encode(
            self.field_frequencies,
            serializer,
        );
        <i64>::sse_encode(self.scan_duration_ms, serializer);
    }
}

impl SseEncode for crate::api::kafka_metadata::TopicMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <i32>::sse_encode(self.partition_count, serializer);
        <i32>::sse_encode(self.replication_factor, serializer);
        <Option<String>>::sse_encode(self.cleanup_policy, serializer);
        <Option<String>>::sse_encode(self.retention_ms, serializer);
    }
}

impl SseEncode for crate::api::kafka_types::TopicPartitionLag {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.topic, serializer);
        <i32>::sse_encode(self.partition, serializer);
        <i64>::sse_encode(self.log_end_offset, serializer);
        <i64>::sse_encode(self.current_offset, serializer);
        <i64>::sse_encode(self.lag, serializer);
    }
}

impl SseEncode for crate::api::kafka_types::TypeOccurrence {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.type_name, serializer);
        <i64>::sse_encode(self.count, serializer);
        <f64>::sse_encode(self.percentage, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use crate::api::kafka_utils::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_kafkalyzer_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_kafkalyzer_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use crate::api::kafka_utils::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
