// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/kafka_analyzer.dart';
import 'api/kafka_consumer.dart';
import 'api/kafka_metadata.dart';
import 'api/kafka_types.dart';
import 'api/kafka_utils.dart';
import 'api/schema_registry.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class KafkalyzerRustLibApiImplPlatform
    extends BaseApiImpl<KafkalyzerRustLibWire> {
  KafkalyzerRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClientConfigPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ClientConfig
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    dynamic raw,
  );

  @protected
  ClientConfig
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    dynamic raw,
  );

  @protected
  RustStreamSink<KafkaMessage> dco_decode_StreamSink_kafka_message_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TopicAnalysisProgress>
  dco_decode_StreamSink_topic_analysis_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ClusterProfile dco_decode_box_autoadd_cluster_profile(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  TopicAnalysisReport dco_decode_box_autoadd_topic_analysis_report(dynamic raw);

  @protected
  ClusterProfile dco_decode_cluster_profile(dynamic raw);

  @protected
  ConsumerGroupLag dco_decode_consumer_group_lag(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FieldOccurrence dco_decode_field_occurrence(dynamic raw);

  @protected
  FieldValueOccurrence dco_decode_field_value_occurrence(dynamic raw);

  @protected
  FilterType dco_decode_filter_type(dynamic raw);

  @protected
  HourlyCount dco_decode_hourly_count(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KafkaHeader dco_decode_kafka_header(dynamic raw);

  @protected
  KafkaMessage dco_decode_kafka_message(dynamic raw);

  @protected
  KeyOccurrence dco_decode_key_occurrence(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConsumerGroupLag> dco_decode_list_consumer_group_lag(dynamic raw);

  @protected
  List<FieldOccurrence> dco_decode_list_field_occurrence(dynamic raw);

  @protected
  List<FieldValueOccurrence> dco_decode_list_field_value_occurrence(
    dynamic raw,
  );

  @protected
  List<HourlyCount> dco_decode_list_hourly_count(dynamic raw);

  @protected
  List<KafkaHeader> dco_decode_list_kafka_header(dynamic raw);

  @protected
  List<KeyOccurrence> dco_decode_list_key_occurrence(dynamic raw);

  @protected
  List<PartitionAnalysis> dco_decode_list_partition_analysis(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TopicMetadata> dco_decode_list_topic_metadata(dynamic raw);

  @protected
  List<TopicPartitionLag> dco_decode_list_topic_partition_lag(dynamic raw);

  @protected
  List<TypeOccurrence> dco_decode_list_type_occurrence(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  TopicAnalysisReport? dco_decode_opt_box_autoadd_topic_analysis_report(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<KafkaHeader>? dco_decode_opt_list_kafka_header(dynamic raw);

  @protected
  PartitionAnalysis dco_decode_partition_analysis(dynamic raw);

  @protected
  SearchScope dco_decode_search_scope(dynamic raw);

  @protected
  TopicAnalysisProgress dco_decode_topic_analysis_progress(dynamic raw);

  @protected
  TopicAnalysisReport dco_decode_topic_analysis_report(dynamic raw);

  @protected
  TopicMetadata dco_decode_topic_metadata(dynamic raw);

  @protected
  TopicPartitionLag dco_decode_topic_partition_lag(dynamic raw);

  @protected
  TypeOccurrence dco_decode_type_occurrence(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ClientConfig
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    SseDeserializer deserializer,
  );

  @protected
  ClientConfig
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<KafkaMessage> sse_decode_StreamSink_kafka_message_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TopicAnalysisProgress>
  sse_decode_StreamSink_topic_analysis_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ClusterProfile sse_decode_box_autoadd_cluster_profile(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TopicAnalysisReport sse_decode_box_autoadd_topic_analysis_report(
    SseDeserializer deserializer,
  );

  @protected
  ClusterProfile sse_decode_cluster_profile(SseDeserializer deserializer);

  @protected
  ConsumerGroupLag sse_decode_consumer_group_lag(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FieldOccurrence sse_decode_field_occurrence(SseDeserializer deserializer);

  @protected
  FieldValueOccurrence sse_decode_field_value_occurrence(
    SseDeserializer deserializer,
  );

  @protected
  FilterType sse_decode_filter_type(SseDeserializer deserializer);

  @protected
  HourlyCount sse_decode_hourly_count(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KafkaHeader sse_decode_kafka_header(SseDeserializer deserializer);

  @protected
  KafkaMessage sse_decode_kafka_message(SseDeserializer deserializer);

  @protected
  KeyOccurrence sse_decode_key_occurrence(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConsumerGroupLag> sse_decode_list_consumer_group_lag(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldOccurrence> sse_decode_list_field_occurrence(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldValueOccurrence> sse_decode_list_field_value_occurrence(
    SseDeserializer deserializer,
  );

  @protected
  List<HourlyCount> sse_decode_list_hourly_count(SseDeserializer deserializer);

  @protected
  List<KafkaHeader> sse_decode_list_kafka_header(SseDeserializer deserializer);

  @protected
  List<KeyOccurrence> sse_decode_list_key_occurrence(
    SseDeserializer deserializer,
  );

  @protected
  List<PartitionAnalysis> sse_decode_list_partition_analysis(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TopicMetadata> sse_decode_list_topic_metadata(
    SseDeserializer deserializer,
  );

  @protected
  List<TopicPartitionLag> sse_decode_list_topic_partition_lag(
    SseDeserializer deserializer,
  );

  @protected
  List<TypeOccurrence> sse_decode_list_type_occurrence(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TopicAnalysisReport? sse_decode_opt_box_autoadd_topic_analysis_report(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<KafkaHeader>? sse_decode_opt_list_kafka_header(
    SseDeserializer deserializer,
  );

  @protected
  PartitionAnalysis sse_decode_partition_analysis(SseDeserializer deserializer);

  @protected
  SearchScope sse_decode_search_scope(SseDeserializer deserializer);

  @protected
  TopicAnalysisProgress sse_decode_topic_analysis_progress(
    SseDeserializer deserializer,
  );

  @protected
  TopicAnalysisReport sse_decode_topic_analysis_report(
    SseDeserializer deserializer,
  );

  @protected
  TopicMetadata sse_decode_topic_metadata(SseDeserializer deserializer);

  @protected
  TopicPartitionLag sse_decode_topic_partition_lag(
    SseDeserializer deserializer,
  );

  @protected
  TypeOccurrence sse_decode_type_occurrence(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_kafka_message_Sse(
    RustStreamSink<KafkaMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_topic_analysis_progress_Sse(
    RustStreamSink<TopicAnalysisProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cluster_profile(
    ClusterProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_topic_analysis_report(
    TopicAnalysisReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cluster_profile(
    ClusterProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_consumer_group_lag(
    ConsumerGroupLag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_field_occurrence(
    FieldOccurrence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_value_occurrence(
    FieldValueOccurrence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_filter_type(FilterType self, SseSerializer serializer);

  @protected
  void sse_encode_hourly_count(HourlyCount self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_kafka_header(KafkaHeader self, SseSerializer serializer);

  @protected
  void sse_encode_kafka_message(KafkaMessage self, SseSerializer serializer);

  @protected
  void sse_encode_key_occurrence(KeyOccurrence self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_consumer_group_lag(
    List<ConsumerGroupLag> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_occurrence(
    List<FieldOccurrence> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_value_occurrence(
    List<FieldValueOccurrence> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hourly_count(
    List<HourlyCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_kafka_header(
    List<KafkaHeader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_key_occurrence(
    List<KeyOccurrence> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_partition_analysis(
    List<PartitionAnalysis> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_topic_metadata(
    List<TopicMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_topic_partition_lag(
    List<TopicPartitionLag> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_type_occurrence(
    List<TypeOccurrence> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_topic_analysis_report(
    TopicAnalysisReport? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_kafka_header(
    List<KafkaHeader>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_partition_analysis(
    PartitionAnalysis self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_scope(SearchScope self, SseSerializer serializer);

  @protected
  void sse_encode_topic_analysis_progress(
    TopicAnalysisProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_topic_analysis_report(
    TopicAnalysisReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_topic_metadata(TopicMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_topic_partition_lag(
    TopicPartitionLag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_type_occurrence(
    TypeOccurrence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class KafkalyzerRustLibWire implements BaseWire {
  KafkalyzerRustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
        ptr,
      );
}

@JS('wasm_bindgen')
external KafkalyzerRustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type KafkalyzerRustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    int ptr,
  );
}
