// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/kafka_consumer.dart';
import 'api/kafka_metadata.dart';
import 'api/kafka_types.dart';
import 'api/kafka_utils.dart';
import 'api/schema_registry.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1945713043;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_kafkalyzer',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<KafkaMessage> crateApiKafkaConsumerConsumeWithFilter({
    required ClusterProfile profile,
    required String topic,
    List<String>? filterTerms,
    String? filterField,
    required FilterType filterType,
    required SearchScope searchScope,
    PlatformInt64? startOffset,
    PlatformInt64? startTimestamp,
    int? startPartition,
    String? fastTraceKey,
    PlatformInt64? endOffset,
    PlatformInt64? endTimestamp,
    int? maxResults,
    required bool runForever,
  });

  Future<ClientConfig> crateApiKafkaUtilsCreateConfig({
    required ClusterProfile profile,
  });

  Future<ConsumerGroupLag> crateApiKafkaMetadataFetchConsumerGroupLag({
    required ClusterProfile profile,
    required String groupId,
  });

  Future<List<ConsumerGroupLag>> crateApiKafkaMetadataFetchConsumerGroups({
    required ClusterProfile profile,
  });

  Future<List<ConsumerGroupLag>> crateApiKafkaMetadataFetchConsumerLags({
    required ClusterProfile profile,
  });

  Future<String> crateApiSchemaRegistryFetchSchema({
    required ClusterProfile profile,
    required String subject,
  });

  Future<List<String>> crateApiSchemaRegistryFetchSubjects({
    required ClusterProfile profile,
  });

  Future<List<TopicMetadata>> crateApiKafkaMetadataFetchTopics({
    required ClusterProfile profile,
  });

  Future<void> crateApiInitApp();

  Future<int> crateApiKafkaUtilsMurmur2({required List<int> data});

  Future<int> crateApiKafkaUtilsToPositive({required int number});

  Future<bool> crateApiKafkaMetadataValidateConnection({
    required ClusterProfile profile,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClientConfig;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClientConfig;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ClientConfigPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<KafkaMessage> crateApiKafkaConsumerConsumeWithFilter({
    required ClusterProfile profile,
    required String topic,
    List<String>? filterTerms,
    String? filterField,
    required FilterType filterType,
    required SearchScope searchScope,
    PlatformInt64? startOffset,
    PlatformInt64? startTimestamp,
    int? startPartition,
    String? fastTraceKey,
    PlatformInt64? endOffset,
    PlatformInt64? endTimestamp,
    int? maxResults,
    required bool runForever,
  }) {
    final sink = RustStreamSink<KafkaMessage>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_cluster_profile(profile, serializer);
            sse_encode_String(topic, serializer);
            sse_encode_opt_list_String(filterTerms, serializer);
            sse_encode_opt_String(filterField, serializer);
            sse_encode_filter_type(filterType, serializer);
            sse_encode_search_scope(searchScope, serializer);
            sse_encode_opt_box_autoadd_i_64(startOffset, serializer);
            sse_encode_opt_box_autoadd_i_64(startTimestamp, serializer);
            sse_encode_opt_box_autoadd_i_32(startPartition, serializer);
            sse_encode_opt_String(fastTraceKey, serializer);
            sse_encode_opt_box_autoadd_i_64(endOffset, serializer);
            sse_encode_opt_box_autoadd_i_64(endTimestamp, serializer);
            sse_encode_opt_box_autoadd_i_32(maxResults, serializer);
            sse_encode_bool(runForever, serializer);
            sse_encode_StreamSink_kafka_message_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiKafkaConsumerConsumeWithFilterConstMeta,
          argValues: [
            profile,
            topic,
            filterTerms,
            filterField,
            filterType,
            searchScope,
            startOffset,
            startTimestamp,
            startPartition,
            fastTraceKey,
            endOffset,
            endTimestamp,
            maxResults,
            runForever,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiKafkaConsumerConsumeWithFilterConstMeta =>
      const TaskConstMeta(
        debugName: "consume_with_filter",
        argNames: [
          "profile",
          "topic",
          "filterTerms",
          "filterField",
          "filterType",
          "searchScope",
          "startOffset",
          "startTimestamp",
          "startPartition",
          "fastTraceKey",
          "endOffset",
          "endTimestamp",
          "maxResults",
          "runForever",
          "sink",
        ],
      );

  @override
  Future<ClientConfig> crateApiKafkaUtilsCreateConfig({
    required ClusterProfile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKafkaUtilsCreateConfigConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaUtilsCreateConfigConstMeta =>
      const TaskConstMeta(debugName: "create_config", argNames: ["profile"]);

  @override
  Future<ConsumerGroupLag> crateApiKafkaMetadataFetchConsumerGroupLag({
    required ClusterProfile profile,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_consumer_group_lag,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKafkaMetadataFetchConsumerGroupLagConstMeta,
        argValues: [profile, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaMetadataFetchConsumerGroupLagConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_consumer_group_lag",
        argNames: ["profile", "groupId"],
      );

  @override
  Future<List<ConsumerGroupLag>> crateApiKafkaMetadataFetchConsumerGroups({
    required ClusterProfile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_consumer_group_lag,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKafkaMetadataFetchConsumerGroupsConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaMetadataFetchConsumerGroupsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_consumer_groups",
        argNames: ["profile"],
      );

  @override
  Future<List<ConsumerGroupLag>> crateApiKafkaMetadataFetchConsumerLags({
    required ClusterProfile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_consumer_group_lag,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKafkaMetadataFetchConsumerLagsConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaMetadataFetchConsumerLagsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_consumer_lags",
        argNames: ["profile"],
      );

  @override
  Future<String> crateApiSchemaRegistryFetchSchema({
    required ClusterProfile profile,
    required String subject,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          sse_encode_String(subject, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSchemaRegistryFetchSchemaConstMeta,
        argValues: [profile, subject],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSchemaRegistryFetchSchemaConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_schema",
        argNames: ["profile", "subject"],
      );

  @override
  Future<List<String>> crateApiSchemaRegistryFetchSubjects({
    required ClusterProfile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSchemaRegistryFetchSubjectsConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSchemaRegistryFetchSubjectsConstMeta =>
      const TaskConstMeta(debugName: "fetch_subjects", argNames: ["profile"]);

  @override
  Future<List<TopicMetadata>> crateApiKafkaMetadataFetchTopics({
    required ClusterProfile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_topic_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKafkaMetadataFetchTopicsConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaMetadataFetchTopicsConstMeta =>
      const TaskConstMeta(debugName: "fetch_topics", argNames: ["profile"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<int> crateApiKafkaUtilsMurmur2({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKafkaUtilsMurmur2ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaUtilsMurmur2ConstMeta =>
      const TaskConstMeta(debugName: "murmur2", argNames: ["data"]);

  @override
  Future<int> crateApiKafkaUtilsToPositive({required int number}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(number, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKafkaUtilsToPositiveConstMeta,
        argValues: [number],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaUtilsToPositiveConstMeta =>
      const TaskConstMeta(debugName: "to_positive", argNames: ["number"]);

  @override
  Future<bool> crateApiKafkaMetadataValidateConnection({
    required ClusterProfile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cluster_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKafkaMetadataValidateConnectionConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKafkaMetadataValidateConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "validate_connection",
        argNames: ["profile"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClientConfig => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClientConfig => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ClientConfig
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientConfigImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClientConfig
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientConfigImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<KafkaMessage> dco_decode_StreamSink_kafka_message_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ClusterProfile dco_decode_box_autoadd_cluster_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_cluster_profile(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ClusterProfile dco_decode_cluster_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 21)
      throw Exception('unexpected arr length: expect 21 but see ${arr.length}');
    return ClusterProfile(
      name: dco_decode_String(arr[0]),
      bootstrapServers: dco_decode_String(arr[1]),
      saslUsername: dco_decode_opt_String(arr[2]),
      saslPassword: dco_decode_opt_String(arr[3]),
      mechanism: dco_decode_opt_String(arr[4]),
      securityProtocol: dco_decode_opt_String(arr[5]),
      schemaRegistryUrl: dco_decode_opt_String(arr[6]),
      sslKeystoreLocation: dco_decode_opt_String(arr[7]),
      sslKeystorePassword: dco_decode_opt_String(arr[8]),
      sslTruststoreLocation: dco_decode_opt_String(arr[9]),
      sslTruststorePassword: dco_decode_opt_String(arr[10]),
      schemaRegistryUsername: dco_decode_opt_String(arr[11]),
      schemaRegistryPassword: dco_decode_opt_String(arr[12]),
      saslKerberosServiceName: dco_decode_opt_String(arr[13]),
      saslKerberosKeytab: dco_decode_opt_String(arr[14]),
      saslKerberosPrincipal: dco_decode_opt_String(arr[15]),
      saslKerberosConf: dco_decode_opt_String(arr[16]),
      saslOauthbearerToken: dco_decode_opt_String(arr[17]),
      sslPemCertificateLocation: dco_decode_opt_String(arr[18]),
      sslPemKeyLocation: dco_decode_opt_String(arr[19]),
      sslPemKeyPassword: dco_decode_opt_String(arr[20]),
    );
  }

  @protected
  ConsumerGroupLag dco_decode_consumer_group_lag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ConsumerGroupLag(
      groupId: dco_decode_String(arr[0]),
      state: dco_decode_String(arr[1]),
      protocolType: dco_decode_String(arr[2]),
      partitionLags: dco_decode_list_topic_partition_lag(arr[3]),
      membersCount: dco_decode_i_32(arr[4]),
      topicsCount: dco_decode_i_32(arr[5]),
    );
  }

  @protected
  FilterType dco_decode_filter_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KafkaHeader dco_decode_kafka_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KafkaHeader(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  KafkaMessage dco_decode_kafka_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return KafkaMessage(
      topic: dco_decode_String(arr[0]),
      partition: dco_decode_i_32(arr[1]),
      offset: dco_decode_i_64(arr[2]),
      key: dco_decode_opt_String(arr[3]),
      payload: dco_decode_opt_String(arr[4]),
      timestamp: dco_decode_i_64(arr[5]),
      headers: dco_decode_opt_list_kafka_header(arr[6]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConsumerGroupLag> dco_decode_list_consumer_group_lag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_consumer_group_lag).toList();
  }

  @protected
  List<KafkaHeader> dco_decode_list_kafka_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_kafka_header).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TopicMetadata> dco_decode_list_topic_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topic_metadata).toList();
  }

  @protected
  List<TopicPartitionLag> dco_decode_list_topic_partition_lag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topic_partition_lag).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  List<KafkaHeader>? dco_decode_opt_list_kafka_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_kafka_header(raw);
  }

  @protected
  SearchScope dco_decode_search_scope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SearchScope.values[raw as int];
  }

  @protected
  TopicMetadata dco_decode_topic_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TopicMetadata(
      name: dco_decode_String(arr[0]),
      partitionCount: dco_decode_i_32(arr[1]),
      replicationFactor: dco_decode_i_32(arr[2]),
      cleanupPolicy: dco_decode_opt_String(arr[3]),
      retentionMs: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  TopicPartitionLag dco_decode_topic_partition_lag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TopicPartitionLag(
      topic: dco_decode_String(arr[0]),
      partition: dco_decode_i_32(arr[1]),
      logEndOffset: dco_decode_i_64(arr[2]),
      currentOffset: dco_decode_i_64(arr[3]),
      lag: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ClientConfig
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientConfigImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClientConfig
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientConfigImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<KafkaMessage> sse_decode_StreamSink_kafka_message_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ClusterProfile sse_decode_box_autoadd_cluster_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_cluster_profile(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ClusterProfile sse_decode_cluster_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_bootstrapServers = sse_decode_String(deserializer);
    var var_saslUsername = sse_decode_opt_String(deserializer);
    var var_saslPassword = sse_decode_opt_String(deserializer);
    var var_mechanism = sse_decode_opt_String(deserializer);
    var var_securityProtocol = sse_decode_opt_String(deserializer);
    var var_schemaRegistryUrl = sse_decode_opt_String(deserializer);
    var var_sslKeystoreLocation = sse_decode_opt_String(deserializer);
    var var_sslKeystorePassword = sse_decode_opt_String(deserializer);
    var var_sslTruststoreLocation = sse_decode_opt_String(deserializer);
    var var_sslTruststorePassword = sse_decode_opt_String(deserializer);
    var var_schemaRegistryUsername = sse_decode_opt_String(deserializer);
    var var_schemaRegistryPassword = sse_decode_opt_String(deserializer);
    var var_saslKerberosServiceName = sse_decode_opt_String(deserializer);
    var var_saslKerberosKeytab = sse_decode_opt_String(deserializer);
    var var_saslKerberosPrincipal = sse_decode_opt_String(deserializer);
    var var_saslKerberosConf = sse_decode_opt_String(deserializer);
    var var_saslOauthbearerToken = sse_decode_opt_String(deserializer);
    var var_sslPemCertificateLocation = sse_decode_opt_String(deserializer);
    var var_sslPemKeyLocation = sse_decode_opt_String(deserializer);
    var var_sslPemKeyPassword = sse_decode_opt_String(deserializer);
    return ClusterProfile(
      name: var_name,
      bootstrapServers: var_bootstrapServers,
      saslUsername: var_saslUsername,
      saslPassword: var_saslPassword,
      mechanism: var_mechanism,
      securityProtocol: var_securityProtocol,
      schemaRegistryUrl: var_schemaRegistryUrl,
      sslKeystoreLocation: var_sslKeystoreLocation,
      sslKeystorePassword: var_sslKeystorePassword,
      sslTruststoreLocation: var_sslTruststoreLocation,
      sslTruststorePassword: var_sslTruststorePassword,
      schemaRegistryUsername: var_schemaRegistryUsername,
      schemaRegistryPassword: var_schemaRegistryPassword,
      saslKerberosServiceName: var_saslKerberosServiceName,
      saslKerberosKeytab: var_saslKerberosKeytab,
      saslKerberosPrincipal: var_saslKerberosPrincipal,
      saslKerberosConf: var_saslKerberosConf,
      saslOauthbearerToken: var_saslOauthbearerToken,
      sslPemCertificateLocation: var_sslPemCertificateLocation,
      sslPemKeyLocation: var_sslPemKeyLocation,
      sslPemKeyPassword: var_sslPemKeyPassword,
    );
  }

  @protected
  ConsumerGroupLag sse_decode_consumer_group_lag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_protocolType = sse_decode_String(deserializer);
    var var_partitionLags = sse_decode_list_topic_partition_lag(deserializer);
    var var_membersCount = sse_decode_i_32(deserializer);
    var var_topicsCount = sse_decode_i_32(deserializer);
    return ConsumerGroupLag(
      groupId: var_groupId,
      state: var_state,
      protocolType: var_protocolType,
      partitionLags: var_partitionLags,
      membersCount: var_membersCount,
      topicsCount: var_topicsCount,
    );
  }

  @protected
  FilterType sse_decode_filter_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FilterType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KafkaHeader sse_decode_kafka_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return KafkaHeader(key: var_key, value: var_value);
  }

  @protected
  KafkaMessage sse_decode_kafka_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_topic = sse_decode_String(deserializer);
    var var_partition = sse_decode_i_32(deserializer);
    var var_offset = sse_decode_i_64(deserializer);
    var var_key = sse_decode_opt_String(deserializer);
    var var_payload = sse_decode_opt_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_headers = sse_decode_opt_list_kafka_header(deserializer);
    return KafkaMessage(
      topic: var_topic,
      partition: var_partition,
      offset: var_offset,
      key: var_key,
      payload: var_payload,
      timestamp: var_timestamp,
      headers: var_headers,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConsumerGroupLag> sse_decode_list_consumer_group_lag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConsumerGroupLag>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_consumer_group_lag(deserializer));
    }
    return ans_;
  }

  @protected
  List<KafkaHeader> sse_decode_list_kafka_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KafkaHeader>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_kafka_header(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TopicMetadata> sse_decode_list_topic_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopicMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topic_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  List<TopicPartitionLag> sse_decode_list_topic_partition_lag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopicPartitionLag>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topic_partition_lag(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<KafkaHeader>? sse_decode_opt_list_kafka_header(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_kafka_header(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchScope sse_decode_search_scope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SearchScope.values[inner];
  }

  @protected
  TopicMetadata sse_decode_topic_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_partitionCount = sse_decode_i_32(deserializer);
    var var_replicationFactor = sse_decode_i_32(deserializer);
    var var_cleanupPolicy = sse_decode_opt_String(deserializer);
    var var_retentionMs = sse_decode_opt_String(deserializer);
    return TopicMetadata(
      name: var_name,
      partitionCount: var_partitionCount,
      replicationFactor: var_replicationFactor,
      cleanupPolicy: var_cleanupPolicy,
      retentionMs: var_retentionMs,
    );
  }

  @protected
  TopicPartitionLag sse_decode_topic_partition_lag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_topic = sse_decode_String(deserializer);
    var var_partition = sse_decode_i_32(deserializer);
    var var_logEndOffset = sse_decode_i_64(deserializer);
    var var_currentOffset = sse_decode_i_64(deserializer);
    var var_lag = sse_decode_i_64(deserializer);
    return TopicPartitionLag(
      topic: var_topic,
      partition: var_partition,
      logEndOffset: var_logEndOffset,
      currentOffset: var_currentOffset,
      lag: var_lag,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    ClientConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientConfigImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientConfig(
    ClientConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientConfigImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_kafka_message_Sse(
    RustStreamSink<KafkaMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_kafka_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_cluster_profile(
    ClusterProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cluster_profile(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_cluster_profile(
    ClusterProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.bootstrapServers, serializer);
    sse_encode_opt_String(self.saslUsername, serializer);
    sse_encode_opt_String(self.saslPassword, serializer);
    sse_encode_opt_String(self.mechanism, serializer);
    sse_encode_opt_String(self.securityProtocol, serializer);
    sse_encode_opt_String(self.schemaRegistryUrl, serializer);
    sse_encode_opt_String(self.sslKeystoreLocation, serializer);
    sse_encode_opt_String(self.sslKeystorePassword, serializer);
    sse_encode_opt_String(self.sslTruststoreLocation, serializer);
    sse_encode_opt_String(self.sslTruststorePassword, serializer);
    sse_encode_opt_String(self.schemaRegistryUsername, serializer);
    sse_encode_opt_String(self.schemaRegistryPassword, serializer);
    sse_encode_opt_String(self.saslKerberosServiceName, serializer);
    sse_encode_opt_String(self.saslKerberosKeytab, serializer);
    sse_encode_opt_String(self.saslKerberosPrincipal, serializer);
    sse_encode_opt_String(self.saslKerberosConf, serializer);
    sse_encode_opt_String(self.saslOauthbearerToken, serializer);
    sse_encode_opt_String(self.sslPemCertificateLocation, serializer);
    sse_encode_opt_String(self.sslPemKeyLocation, serializer);
    sse_encode_opt_String(self.sslPemKeyPassword, serializer);
  }

  @protected
  void sse_encode_consumer_group_lag(
    ConsumerGroupLag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.groupId, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_String(self.protocolType, serializer);
    sse_encode_list_topic_partition_lag(self.partitionLags, serializer);
    sse_encode_i_32(self.membersCount, serializer);
    sse_encode_i_32(self.topicsCount, serializer);
  }

  @protected
  void sse_encode_filter_type(FilterType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_kafka_header(KafkaHeader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_kafka_message(KafkaMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.topic, serializer);
    sse_encode_i_32(self.partition, serializer);
    sse_encode_i_64(self.offset, serializer);
    sse_encode_opt_String(self.key, serializer);
    sse_encode_opt_String(self.payload, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_opt_list_kafka_header(self.headers, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_consumer_group_lag(
    List<ConsumerGroupLag> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_consumer_group_lag(item, serializer);
    }
  }

  @protected
  void sse_encode_list_kafka_header(
    List<KafkaHeader> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_kafka_header(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_topic_metadata(
    List<TopicMetadata> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topic_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_list_topic_partition_lag(
    List<TopicPartitionLag> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topic_partition_lag(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_kafka_header(
    List<KafkaHeader>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_kafka_header(self, serializer);
    }
  }

  @protected
  void sse_encode_search_scope(SearchScope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_topic_metadata(TopicMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_i_32(self.partitionCount, serializer);
    sse_encode_i_32(self.replicationFactor, serializer);
    sse_encode_opt_String(self.cleanupPolicy, serializer);
    sse_encode_opt_String(self.retentionMs, serializer);
  }

  @protected
  void sse_encode_topic_partition_lag(
    TopicPartitionLag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.topic, serializer);
    sse_encode_i_32(self.partition, serializer);
    sse_encode_i_64(self.logEndOffset, serializer);
    sse_encode_i_64(self.currentOffset, serializer);
    sse_encode_i_64(self.lag, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ClientConfigImpl extends RustOpaque implements ClientConfig {
  // Not to be used by end users
  ClientConfigImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClientConfigImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ClientConfig,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientConfig,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientConfigPtr,
  );
}
