// Mocks generated by Mockito from annotations
// in kafkalyzer/test/src/features/schema/presentation/widgets/schema_viewer_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:kafkalyzer/src/features/schema/presentation/controllers/schema_controller.dart'
    as _i2;
import 'package:kafkalyzer/src/rust/api/kafka_types.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SchemaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchemaController extends _i1.Mock implements _i2.SchemaController {
  MockSchemaController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  List<String>? getSchemas(_i3.ClusterProfile? cluster) =>
      (super.noSuchMethod(Invocation.method(#getSchemas, [cluster]))
          as List<String>?);

  @override
  bool isLoading(_i3.ClusterProfile? cluster) =>
      (super.noSuchMethod(
            Invocation.method(#isLoading, [cluster]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> fetchSchemas(
    _i3.ClusterProfile? cluster, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchemas, [cluster], {#force: force}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearCache(_i3.ClusterProfile? cluster) => super.noSuchMethod(
    Invocation.method(#clearCache, [cluster]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<String>> fetchSchemaFields(
    _i3.ClusterProfile? cluster,
    String? topic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchemaFields, [cluster, topic]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<String> fetchSchemaContent(
    _i3.ClusterProfile? cluster,
    String? subject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchemaContent, [cluster, subject]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#fetchSchemaContent, [cluster, subject]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  List<String> parseSchemaFields(String? jsonString) =>
      (super.noSuchMethod(
            Invocation.method(#parseSchemaFields, [jsonString]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
