[package]
name = "kafkalyzer-kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
log = "0.4"
reqwest = { version = "0.12", features = ["json"] }
schema_registry_converter = { version = "=4.2.0", features = ["avro", "json", "proto_decoder"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
tokio = { version = "1.48.0", features = ["full"] }
regex = "1.12.2"
hex = "0.4"
apache-avro = "0.17.0"
protofish = "0.5.3"
kafkalyzer-core = { path = "../kafkalyzer-core" }

# --- WINDOWS KONFIGURATION (vcpkg) ---
[target.'cfg(windows)'.dependencies]
rdkafka = { version = "0.36.2", features = ["ssl", "sasl", "cmake-build"] }
openssl = { version = "0.10", features = [] }
rdkafka-sys = { version = "=4.7.0", features = ["ssl"] }

# --- LINUX KONFIGURATION ---
[target.'cfg(target_os = "linux")'.dependencies]
rdkafka = { version = "0.36.2", features = ["ssl", "sasl", "gssapi"] }
openssl = { version = "0.10", features = [] }
rdkafka-sys = { version = "=4.7.0", features = ["ssl", "sasl"] }

# --- MACOS KONFIGURATION ---
[target.'cfg(target_os = "macos")'.dependencies]
rdkafka = { version = "0.36.2", features = ["ssl-vendored", "gssapi-vendored", "cmake-build"] }
openssl = { version = "0.10", features = ["vendored"] }
sasl2-sys = { version = "0.1", features = ["vendored"] }
