// Mocks generated by Mockito 5.4.6 from annotations
// in kafkalyzer/test/src/features/settings/presentation/settings_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:kafkalyzer/src/features/cluster/presentation/controllers/active_connection_controller.dart'
    as _i8;
import 'package:kafkalyzer/src/features/cluster/presentation/controllers/cluster_list_controller.dart'
    as _i3;
import 'package:kafkalyzer/src/features/topic/presentation/controllers/message_stream_controller.dart'
    as _i2;
import 'package:kafkalyzer/src/rust/api/kafka_metadata.dart' as _i9;
import 'package:kafkalyzer/src/rust/api/kafka_types.dart' as _i4;
import 'package:kafkalyzer/src/services/settings_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageStreamController_0 extends _i1.SmartFake
    implements _i2.MessageStreamController {
  _FakeMessageStreamController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClusterListController].
///
/// See the documentation for Mockito's code generation for more information.
class MockClusterListController extends _i1.Mock
    implements _i3.ClusterListController {
  MockClusterListController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.ClusterProfile> get clusters =>
      (super.noSuchMethod(
            Invocation.getter(#clusters),
            returnValue: <_i4.ClusterProfile>[],
          )
          as List<_i4.ClusterProfile>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> loadClusters() =>
      (super.noSuchMethod(
            Invocation.method(#loadClusters, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addCluster(_i4.ClusterProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#addCluster, [profile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateCluster(
    int? index,
    _i4.ClusterProfile? updatedProfile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCluster, [index, updatedProfile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCluster(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCluster, [index]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> importClustersZip(List<int>? zipBytes) =>
      (super.noSuchMethod(
            Invocation.method(#importClustersZip, [zipBytes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> importClusters(String? jsonString) =>
      (super.noSuchMethod(
            Invocation.method(#importClusters, [jsonString]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<int>> exportClustersZip(
    List<_i4.ClusterProfile>? clustersToExport,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportClustersZip, [clustersToExport]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  String exportClusters(List<_i4.ClusterProfile>? clustersToExport) =>
      (super.noSuchMethod(
            Invocation.method(#exportClusters, [clustersToExport]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#exportClusters, [clustersToExport]),
            ),
          )
          as String);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ActiveConnectionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockActiveConnectionController extends _i1.Mock
    implements _i8.ActiveConnectionController {
  MockActiveConnectionController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get showInternalTopics =>
      (super.noSuchMethod(
            Invocation.getter(#showInternalTopics),
            returnValue: false,
          )
          as bool);

  @override
  bool get showStreamTopics =>
      (super.noSuchMethod(
            Invocation.getter(#showStreamTopics),
            returnValue: false,
          )
          as bool);

  @override
  String get topicFilter =>
      (super.noSuchMethod(
            Invocation.getter(#topicFilter),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#topicFilter),
            ),
          )
          as String);

  @override
  List<_i9.TopicMetadata> get topics =>
      (super.noSuchMethod(
            Invocation.getter(#topics),
            returnValue: <_i9.TopicMetadata>[],
          )
          as List<_i9.TopicMetadata>);

  @override
  bool get isConnecting =>
      (super.noSuchMethod(Invocation.getter(#isConnecting), returnValue: false)
          as bool);

  @override
  List<_i8.OpenTopicRecord> get openTopics =>
      (super.noSuchMethod(
            Invocation.getter(#openTopics),
            returnValue: <_i8.OpenTopicRecord>[],
          )
          as List<_i8.OpenTopicRecord>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void toggleShowInternalTopics(bool? value) => super.noSuchMethod(
    Invocation.method(#toggleShowInternalTopics, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleShowStreamTopics(bool? value) => super.noSuchMethod(
    Invocation.method(#toggleShowStreamTopics, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateTopicFilter(String? filter) => super.noSuchMethod(
    Invocation.method(#updateTopicFilter, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  void setActiveTopic(
    _i9.TopicMetadata? topic, [
    _i4.ClusterProfile? profile,
  ]) => super.noSuchMethod(
    Invocation.method(#setActiveTopic, [topic, profile]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.MessageStreamController getStreamController(
    String? topicName,
    String? clusterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStreamController, [topicName, clusterName]),
            returnValue: _FakeMessageStreamController_0(
              this,
              Invocation.method(#getStreamController, [topicName, clusterName]),
            ),
          )
          as _i2.MessageStreamController);

  @override
  void closeTopic(_i9.TopicMetadata? topic, String? clusterName) =>
      super.noSuchMethod(
        Invocation.method(#closeTopic, [topic, clusterName]),
        returnValueForMissingStub: null,
      );

  @override
  void clearOpenTopics() => super.noSuchMethod(
    Invocation.method(#clearOpenTopics, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> connect(_i4.ClusterProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [profile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i10.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> exportConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#exportConfiguration, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> importConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#importConfiguration, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
