// GENERATED by scripts/gen_flex_theme_bridge.py -- do not edit by hand.
// Bridges legacy `package:flutter/material` ThemeData (as produced by
// flex_color_scheme, which has not yet migrated to package:material_ui) into
// the modern `package:material_ui` ThemeData expected by Flutter 3.47+ apps.
//
// See https://github.com/rydmike/flex_color_scheme/issues/310
//
import 'package:flutter/material.dart' as legacy;
import 'package:material_ui/material_ui.dart' as modern;

modern.FloatingLabelAlignment _mapFloatingLabelAlignment(
  legacy.FloatingLabelAlignment? v,
) {
  // material_ui.FloatingLabelAlignment has no `end`; map it to the legacy default.
  if (v == legacy.FloatingLabelAlignment.center) {
    return modern.FloatingLabelAlignment.center;
  }
  return modern.FloatingLabelAlignment.start;
}

modern.InputBorder? _mapInputBorder(legacy.InputBorder? v) {
  if (v == null) return null;
  if (v is legacy.UnderlineInputBorder) {
    return const modern.UnderlineInputBorder();
  }
  if (v is legacy.OutlineInputBorder) {
    return modern.OutlineInputBorder(
      borderRadius: v.borderRadius,
      gapPadding: v.gapPadding,
      borderSide: v.borderSide,
    );
  }
  return null;
}

modern.InputDecorationThemeData? _mapInputDecorationThemeDataObject(Object? v) {
  if (v == null) return null;
  final legacy.InputDecorationThemeData data = v is legacy.InputDecorationTheme
      ? (v).data
      : v as legacy.InputDecorationThemeData;
  return _mapInputDecorationThemeData(data);
}

modern.AppBarThemeData? _mapAppBarThemeDataObject(Object? v) {
  if (v == null) return null;
  final legacy.AppBarThemeData data = v is legacy.AppBarTheme
      ? (v).data
      : v as legacy.AppBarThemeData;
  return _mapAppBarThemeData(data);
}

modern.SliderComponentShape? _mapSliderComponentShapeShapes(
  legacy.SliderComponentShape? v,
) {
  if (v == null) return null;
  if (v is legacy.DropSliderValueIndicatorShape) {
    return const modern.DropSliderValueIndicatorShape();
  }
  if (v is legacy.RectangularSliderValueIndicatorShape) {
    return const modern.RectangularSliderValueIndicatorShape();
  }
  if (v is legacy.RoundedRectSliderValueIndicatorShape) {
    return const modern.RoundedRectSliderValueIndicatorShape();
  }
  return null;
}

modern.RangeSliderValueIndicatorShape? _mapRangeSliderValueIndicatorShapeShapes(
  legacy.RangeSliderValueIndicatorShape? v,
) {
  if (v == null) return null;
  if (v is legacy.PaddleRangeSliderValueIndicatorShape) {
    return const modern.PaddleRangeSliderValueIndicatorShape();
  }
  if (v is legacy.RectangularRangeSliderValueIndicatorShape) {
    return const modern.RectangularRangeSliderValueIndicatorShape();
  }
  if (v is legacy.RoundedRectRangeSliderValueIndicatorShape) {
    return const modern.RoundedRectRangeSliderValueIndicatorShape();
  }
  return null;
}

modern.PageTransitionsTheme _mapPageTransitionsTheme(
  legacy.PageTransitionsTheme t,
) {
  return modern.PageTransitionsTheme();
}

modern.ScrollbarThemeData _mapScrollbarThemeData(legacy.ScrollbarThemeData t) {
  return modern.ScrollbarThemeData(
    thumbVisibility: t.thumbVisibility,
    thickness: t.thickness,
    trackVisibility: t.trackVisibility,
    radius: t.radius,
    thumbColor: t.thumbColor,
    trackColor: t.trackColor,
    trackBorderColor: t.trackBorderColor,
    crossAxisMargin: t.crossAxisMargin,
    mainAxisMargin: t.mainAxisMargin,
    minThumbLength: t.minThumbLength,
    interactive: t.interactive,
  );
}

modern.ColorScheme _mapColorScheme(legacy.ColorScheme t) {
  return modern.ColorScheme(
    brightness: t.brightness,
    primary: t.primary,
    onPrimary: t.onPrimary,
    primaryContainer: t.primaryContainer,
    onPrimaryContainer: t.onPrimaryContainer,
    primaryFixed: t.primaryFixed,
    primaryFixedDim: t.primaryFixedDim,
    onPrimaryFixed: t.onPrimaryFixed,
    onPrimaryFixedVariant: t.onPrimaryFixedVariant,
    secondary: t.secondary,
    onSecondary: t.onSecondary,
    secondaryContainer: t.secondaryContainer,
    onSecondaryContainer: t.onSecondaryContainer,
    secondaryFixed: t.secondaryFixed,
    secondaryFixedDim: t.secondaryFixedDim,
    onSecondaryFixed: t.onSecondaryFixed,
    onSecondaryFixedVariant: t.onSecondaryFixedVariant,
    tertiary: t.tertiary,
    onTertiary: t.onTertiary,
    tertiaryContainer: t.tertiaryContainer,
    onTertiaryContainer: t.onTertiaryContainer,
    tertiaryFixed: t.tertiaryFixed,
    tertiaryFixedDim: t.tertiaryFixedDim,
    onTertiaryFixed: t.onTertiaryFixed,
    onTertiaryFixedVariant: t.onTertiaryFixedVariant,
    error: t.error,
    onError: t.onError,
    errorContainer: t.errorContainer,
    onErrorContainer: t.onErrorContainer,
    surface: t.surface,
    onSurface: t.onSurface,
    surfaceDim: t.surfaceDim,
    surfaceBright: t.surfaceBright,
    surfaceContainerLowest: t.surfaceContainerLowest,
    surfaceContainerLow: t.surfaceContainerLow,
    surfaceContainer: t.surfaceContainer,
    surfaceContainerHigh: t.surfaceContainerHigh,
    surfaceContainerHighest: t.surfaceContainerHighest,
    onSurfaceVariant: t.onSurfaceVariant,
    outline: t.outline,
    outlineVariant: t.outlineVariant,
    shadow: t.shadow,
    scrim: t.scrim,
    inverseSurface: t.inverseSurface,
    onInverseSurface: t.onInverseSurface,
    inversePrimary: t.inversePrimary,
    surfaceTint: t.surfaceTint,
  );
}

modern.TextTheme _mapTextTheme(legacy.TextTheme t) {
  return modern.TextTheme(
    displayLarge: t.displayLarge,
    displayMedium: t.displayMedium,
    displaySmall: t.displaySmall,
    headlineLarge: t.headlineLarge,
    headlineMedium: t.headlineMedium,
    headlineSmall: t.headlineSmall,
    titleLarge: t.titleLarge,
    titleMedium: t.titleMedium,
    titleSmall: t.titleSmall,
    bodyLarge: t.bodyLarge,
    bodyMedium: t.bodyMedium,
    bodySmall: t.bodySmall,
    labelLarge: t.labelLarge,
    labelMedium: t.labelMedium,
    labelSmall: t.labelSmall,
  );
}

modern.Typography _mapTypography(legacy.Typography t) {
  return modern.Typography(
    black: _mapTextTheme(t.black),
    white: _mapTextTheme(t.white),
    englishLike: _mapTextTheme(t.englishLike),
    dense: _mapTextTheme(t.dense),
    tall: _mapTextTheme(t.tall),
  );
}

modern.ActionIconThemeData _mapActionIconThemeData(
  legacy.ActionIconThemeData t,
) {
  return modern.ActionIconThemeData();
}

modern.BadgeThemeData _mapBadgeThemeData(legacy.BadgeThemeData t) {
  return modern.BadgeThemeData(
    backgroundColor: t.backgroundColor,
    textColor: t.textColor,
    smallSize: t.smallSize,
    largeSize: t.largeSize,
    textStyle: t.textStyle,
    padding: t.padding,
    alignment: t.alignment,
    offset: t.offset,
  );
}

modern.MaterialBannerThemeData _mapMaterialBannerThemeData(
  legacy.MaterialBannerThemeData t,
) {
  return modern.MaterialBannerThemeData(
    backgroundColor: t.backgroundColor,
    surfaceTintColor: t.surfaceTintColor,
    shadowColor: t.shadowColor,
    dividerColor: t.dividerColor,
    contentTextStyle: t.contentTextStyle,
    elevation: t.elevation,
    padding: t.padding,
    leadingPadding: t.leadingPadding,
  );
}

modern.BottomAppBarThemeData _mapBottomAppBarThemeData(
  legacy.BottomAppBarThemeData t,
) {
  return modern.BottomAppBarThemeData(
    color: t.color,
    elevation: t.elevation,
    shape: t.shape,
    height: t.height,
    surfaceTintColor: t.surfaceTintColor,
    shadowColor: t.shadowColor,
    padding: t.padding,
  );
}

modern.BottomNavigationBarThemeData _mapBottomNavigationBarThemeData(
  legacy.BottomNavigationBarThemeData t,
) {
  return modern.BottomNavigationBarThemeData(
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    selectedIconTheme: t.selectedIconTheme,
    unselectedIconTheme: t.unselectedIconTheme,
    selectedItemColor: t.selectedItemColor,
    unselectedItemColor: t.unselectedItemColor,
    selectedLabelStyle: t.selectedLabelStyle,
    unselectedLabelStyle: t.unselectedLabelStyle,
    showSelectedLabels: t.showSelectedLabels,
    showUnselectedLabels: t.showUnselectedLabels,
    type: t.type == null
        ? null
        : modern.BottomNavigationBarType.values[legacy
              .BottomNavigationBarType
              .values
              .indexOf(t.type!)],
    enableFeedback: t.enableFeedback,
    landscapeLayout: t.landscapeLayout == null
        ? null
        : modern.BottomNavigationBarLandscapeLayout.values[legacy
              .BottomNavigationBarLandscapeLayout
              .values
              .indexOf(t.landscapeLayout!)],
    mouseCursor: t.mouseCursor,
  );
}

modern.BottomSheetThemeData _mapBottomSheetThemeData(
  legacy.BottomSheetThemeData t,
) {
  return modern.BottomSheetThemeData(
    backgroundColor: t.backgroundColor,
    surfaceTintColor: t.surfaceTintColor,
    elevation: t.elevation,
    modalBackgroundColor: t.modalBackgroundColor,
    modalBarrierColor: t.modalBarrierColor,
    shadowColor: t.shadowColor,
    modalElevation: t.modalElevation,
    shape: t.shape,
    showDragHandle: t.showDragHandle,
    dragHandleColor: t.dragHandleColor,
    dragHandleSize: t.dragHandleSize,
    clipBehavior: t.clipBehavior,
    constraints: t.constraints,
  );
}

modern.ButtonThemeData _mapButtonThemeData(legacy.ButtonThemeData t) {
  return modern.ButtonThemeData(
    textTheme: modern
        .ButtonTextTheme
        .values[legacy.ButtonTextTheme.values.indexOf(t.textTheme)],
    minWidth: t.minWidth,
    height: t.height,
    padding: t.padding,
    shape: t.shape,
    layoutBehavior:
        modern.ButtonBarLayoutBehavior.values[legacy
            .ButtonBarLayoutBehavior
            .values
            .indexOf(t.layoutBehavior)],
    alignedDropdown: t.alignedDropdown,
    colorScheme: t.colorScheme == null ? null : _mapColorScheme(t.colorScheme!),
  );
}

modern.CardThemeData _mapCardThemeData(legacy.CardThemeData t) {
  return modern.CardThemeData(
    clipBehavior: t.clipBehavior,
    color: t.color,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    elevation: t.elevation,
    margin: t.margin,
    shape: t.shape,
  );
}

modern.CarouselViewThemeData _mapCarouselViewThemeData(
  legacy.CarouselViewThemeData t,
) {
  return modern.CarouselViewThemeData(
    elevation: t.elevation,
    backgroundColor: t.backgroundColor,
    overlayColor: t.overlayColor,
    shape: t.shape,
    padding: t.padding,
    itemClipBehavior: t.itemClipBehavior,
  );
}

modern.CheckboxThemeData _mapCheckboxThemeData(legacy.CheckboxThemeData t) {
  return modern.CheckboxThemeData(
    mouseCursor: t.mouseCursor,
    fillColor: t.fillColor,
    checkColor: t.checkColor,
    overlayColor: t.overlayColor,
    splashRadius: t.splashRadius,
    materialTapTargetSize: t.materialTapTargetSize == null
        ? null
        : modern.MaterialTapTargetSize.values[legacy
              .MaterialTapTargetSize
              .values
              .indexOf(t.materialTapTargetSize!)],
    visualDensity: t.visualDensity == null
        ? null
        : _mapVisualDensity(t.visualDensity!),
    shape: t.shape,
    side: t.side,
  );
}

modern.ChipThemeData _mapChipThemeData(legacy.ChipThemeData t) {
  return modern.ChipThemeData(
    color: t.color,
    backgroundColor: t.backgroundColor,
    deleteIconColor: t.deleteIconColor,
    disabledColor: t.disabledColor,
    selectedColor: t.selectedColor,
    secondarySelectedColor: t.secondarySelectedColor,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    selectedShadowColor: t.selectedShadowColor,
    showCheckmark: t.showCheckmark,
    checkmarkColor: t.checkmarkColor,
    labelPadding: t.labelPadding,
    padding: t.padding,
    side: t.side,
    shape: t.shape,
    labelStyle: t.labelStyle,
    secondaryLabelStyle: t.secondaryLabelStyle,
    brightness: t.brightness,
    elevation: t.elevation,
    pressElevation: t.pressElevation,
    iconTheme: t.iconTheme,
    avatarBoxConstraints: t.avatarBoxConstraints,
    deleteIconBoxConstraints: t.deleteIconBoxConstraints,
  );
}

modern.DataTableThemeData _mapDataTableThemeData(legacy.DataTableThemeData t) {
  return modern.DataTableThemeData(
    decoration: t.decoration,
    dataRowColor: t.dataRowColor,
    dataRowMinHeight: t.dataRowMinHeight,
    dataRowMaxHeight: t.dataRowMaxHeight,
    dataTextStyle: t.dataTextStyle,
    headingRowColor: t.headingRowColor,
    headingRowHeight: t.headingRowHeight,
    headingTextStyle: t.headingTextStyle,
    horizontalMargin: t.horizontalMargin,
    columnSpacing: t.columnSpacing,
    dividerThickness: t.dividerThickness,
    checkboxHorizontalMargin: t.checkboxHorizontalMargin,
    headingCellCursor: t.headingCellCursor,
    dataRowCursor: t.dataRowCursor,
    headingRowAlignment: t.headingRowAlignment,
  );
}

modern.DatePickerThemeData _mapDatePickerThemeData(
  legacy.DatePickerThemeData t,
) {
  return modern.DatePickerThemeData(
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    shape: t.shape,
    headerBackgroundColor: t.headerBackgroundColor,
    headerForegroundColor: t.headerForegroundColor,
    headerHeadlineStyle: t.headerHeadlineStyle,
    headerHelpStyle: t.headerHelpStyle,
    weekdayStyle: t.weekdayStyle,
    dayStyle: t.dayStyle,
    dayForegroundColor: t.dayForegroundColor,
    dayBackgroundColor: t.dayBackgroundColor,
    dayOverlayColor: t.dayOverlayColor,
    dayShape: t.dayShape,
    todayForegroundColor: t.todayForegroundColor,
    todayBackgroundColor: t.todayBackgroundColor,
    todayBorder: t.todayBorder,
    yearStyle: t.yearStyle,
    yearForegroundColor: t.yearForegroundColor,
    yearBackgroundColor: t.yearBackgroundColor,
    yearOverlayColor: t.yearOverlayColor,
    yearShape: t.yearShape,
    rangePickerBackgroundColor: t.rangePickerBackgroundColor,
    rangePickerElevation: t.rangePickerElevation,
    rangePickerShadowColor: t.rangePickerShadowColor,
    rangePickerSurfaceTintColor: t.rangePickerSurfaceTintColor,
    rangePickerShape: t.rangePickerShape,
    rangePickerHeaderBackgroundColor: t.rangePickerHeaderBackgroundColor,
    rangePickerHeaderForegroundColor: t.rangePickerHeaderForegroundColor,
    rangePickerHeaderHeadlineStyle: t.rangePickerHeaderHeadlineStyle,
    rangePickerHeaderHelpStyle: t.rangePickerHeaderHelpStyle,
    rangeSelectionBackgroundColor: t.rangeSelectionBackgroundColor,
    rangeSelectionOverlayColor: t.rangeSelectionOverlayColor,
    dividerColor: t.dividerColor,
    inputDecorationTheme: _mapInputDecorationThemeDataObject(
      t.inputDecorationTheme,
    ),
    cancelButtonStyle: t.cancelButtonStyle == null
        ? null
        : _mapButtonStyle(t.cancelButtonStyle!),
    confirmButtonStyle: t.confirmButtonStyle == null
        ? null
        : _mapButtonStyle(t.confirmButtonStyle!),
    locale: t.locale,
    toggleButtonTextStyle: t.toggleButtonTextStyle,
    subHeaderForegroundColor: t.subHeaderForegroundColor,
  );
}

modern.DialogThemeData _mapDialogThemeData(legacy.DialogThemeData t) {
  return modern.DialogThemeData(
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    shape: t.shape,
    alignment: t.alignment,
    iconColor: t.iconColor,
    titleTextStyle: t.titleTextStyle,
    contentTextStyle: t.contentTextStyle,
    actionsPadding: t.actionsPadding,
    barrierColor: t.barrierColor,
    insetPadding: t.insetPadding,
    clipBehavior: t.clipBehavior,
    constraints: t.constraints,
  );
}

modern.DividerThemeData _mapDividerThemeData(legacy.DividerThemeData t) {
  return modern.DividerThemeData(
    color: t.color,
    space: t.space,
    thickness: t.thickness,
    indent: t.indent,
    endIndent: t.endIndent,
    radius: t.radius,
  );
}

modern.DrawerThemeData _mapDrawerThemeData(legacy.DrawerThemeData t) {
  return modern.DrawerThemeData(
    backgroundColor: t.backgroundColor,
    scrimColor: t.scrimColor,
    elevation: t.elevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    shape: t.shape,
    endShape: t.endShape,
    width: t.width,
    clipBehavior: t.clipBehavior,
  );
}

modern.DropdownMenuThemeData _mapDropdownMenuThemeData(
  legacy.DropdownMenuThemeData t,
) {
  return modern.DropdownMenuThemeData(
    textStyle: t.textStyle,
    inputDecorationTheme: _mapInputDecorationThemeDataObject(
      t.inputDecorationTheme,
    ),
    menuStyle: t.menuStyle == null ? null : _mapMenuStyle(t.menuStyle!),
    disabledColor: t.disabledColor,
  );
}

modern.ElevatedButtonThemeData _mapElevatedButtonThemeData(
  legacy.ElevatedButtonThemeData t,
) {
  return modern.ElevatedButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
  );
}

modern.ExpansionTileThemeData _mapExpansionTileThemeData(
  legacy.ExpansionTileThemeData t,
) {
  return modern.ExpansionTileThemeData(
    backgroundColor: t.backgroundColor,
    collapsedBackgroundColor: t.collapsedBackgroundColor,
    tilePadding: t.tilePadding,
    expandedAlignment: t.expandedAlignment,
    childrenPadding: t.childrenPadding,
    iconColor: t.iconColor,
    collapsedIconColor: t.collapsedIconColor,
    textColor: t.textColor,
    collapsedTextColor: t.collapsedTextColor,
    shape: t.shape,
    collapsedShape: t.collapsedShape,
    clipBehavior: t.clipBehavior,
    expansionAnimationStyle: t.expansionAnimationStyle,
  );
}

modern.FilledButtonThemeData _mapFilledButtonThemeData(
  legacy.FilledButtonThemeData t,
) {
  return modern.FilledButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
  );
}

modern.FloatingActionButtonThemeData _mapFloatingActionButtonThemeData(
  legacy.FloatingActionButtonThemeData t,
) {
  return modern.FloatingActionButtonThemeData(
    foregroundColor: t.foregroundColor,
    backgroundColor: t.backgroundColor,
    focusColor: t.focusColor,
    hoverColor: t.hoverColor,
    splashColor: t.splashColor,
    elevation: t.elevation,
    focusElevation: t.focusElevation,
    hoverElevation: t.hoverElevation,
    disabledElevation: t.disabledElevation,
    highlightElevation: t.highlightElevation,
    shape: t.shape,
    enableFeedback: t.enableFeedback,
    iconSize: t.iconSize,
    sizeConstraints: t.sizeConstraints,
    smallSizeConstraints: t.smallSizeConstraints,
    largeSizeConstraints: t.largeSizeConstraints,
    extendedSizeConstraints: t.extendedSizeConstraints,
    extendedIconLabelSpacing: t.extendedIconLabelSpacing,
    extendedPadding: t.extendedPadding,
    extendedTextStyle: t.extendedTextStyle,
    mouseCursor: t.mouseCursor,
  );
}

modern.IconButtonThemeData _mapIconButtonThemeData(
  legacy.IconButtonThemeData t,
) {
  return modern.IconButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
  );
}

modern.ListTileThemeData _mapListTileThemeData(legacy.ListTileThemeData t) {
  return modern.ListTileThemeData(
    dense: t.dense,
    shape: t.shape,
    style: t.style == null
        ? null
        : modern.ListTileStyle.values[legacy.ListTileStyle.values.indexOf(
            t.style!,
          )],
    selectedColor: t.selectedColor,
    iconColor: t.iconColor,
    textColor: t.textColor,
    titleTextStyle: t.titleTextStyle,
    subtitleTextStyle: t.subtitleTextStyle,
    leadingAndTrailingTextStyle: t.leadingAndTrailingTextStyle,
    contentPadding: t.contentPadding,
    tileColor: t.tileColor,
    selectedTileColor: t.selectedTileColor,
    horizontalTitleGap: t.horizontalTitleGap,
    minVerticalPadding: t.minVerticalPadding,
    minLeadingWidth: t.minLeadingWidth,
    enableFeedback: t.enableFeedback,
    mouseCursor: t.mouseCursor,
    visualDensity: t.visualDensity == null
        ? null
        : _mapVisualDensity(t.visualDensity!),
    minTileHeight: t.minTileHeight,
    titleAlignment: t.titleAlignment == null
        ? null
        : modern.ListTileTitleAlignment.values[legacy
              .ListTileTitleAlignment
              .values
              .indexOf(t.titleAlignment!)],
    controlAffinity: t.controlAffinity == null
        ? null
        : modern.ListTileControlAffinity.values[legacy
              .ListTileControlAffinity
              .values
              .indexOf(t.controlAffinity!)],
    isThreeLine: t.isThreeLine,
  );
}

modern.MenuBarThemeData _mapMenuBarThemeData(legacy.MenuBarThemeData t) {
  return modern.MenuBarThemeData();
}

modern.MenuButtonThemeData _mapMenuButtonThemeData(
  legacy.MenuButtonThemeData t,
) {
  return modern.MenuButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
  );
}

modern.MenuThemeData _mapMenuThemeData(legacy.MenuThemeData t) {
  return modern.MenuThemeData(
    style: t.style == null ? null : _mapMenuStyle(t.style!),
    submenuIcon: t.submenuIcon,
  );
}

modern.NavigationBarThemeData _mapNavigationBarThemeData(
  legacy.NavigationBarThemeData t,
) {
  return modern.NavigationBarThemeData(
    height: t.height,
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    indicatorColor: t.indicatorColor,
    indicatorShape: t.indicatorShape,
    labelTextStyle: t.labelTextStyle,
    iconTheme: t.iconTheme,
    labelBehavior: t.labelBehavior == null
        ? null
        : modern.NavigationDestinationLabelBehavior.values[legacy
              .NavigationDestinationLabelBehavior
              .values
              .indexOf(t.labelBehavior!)],
    overlayColor: t.overlayColor,
    labelPadding: t.labelPadding,
  );
}

modern.NavigationDrawerThemeData _mapNavigationDrawerThemeData(
  legacy.NavigationDrawerThemeData t,
) {
  return modern.NavigationDrawerThemeData(
    tileHeight: t.tileHeight,
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    indicatorColor: t.indicatorColor,
    indicatorShape: t.indicatorShape,
    indicatorSize: t.indicatorSize,
    labelTextStyle: t.labelTextStyle,
    iconTheme: t.iconTheme,
  );
}

modern.NavigationRailThemeData _mapNavigationRailThemeData(
  legacy.NavigationRailThemeData t,
) {
  return modern.NavigationRailThemeData(
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    unselectedLabelTextStyle: t.unselectedLabelTextStyle,
    selectedLabelTextStyle: t.selectedLabelTextStyle,
    unselectedIconTheme: t.unselectedIconTheme,
    selectedIconTheme: t.selectedIconTheme,
    groupAlignment: t.groupAlignment,
    labelType: t.labelType == null
        ? null
        : modern.NavigationRailLabelType.values[legacy
              .NavigationRailLabelType
              .values
              .indexOf(t.labelType!)],
    useIndicator: t.useIndicator,
    indicatorColor: t.indicatorColor,
    indicatorShape: t.indicatorShape,
    minWidth: t.minWidth,
    minExtendedWidth: t.minExtendedWidth,
  );
}

modern.OutlinedButtonThemeData _mapOutlinedButtonThemeData(
  legacy.OutlinedButtonThemeData t,
) {
  return modern.OutlinedButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
  );
}

modern.PopupMenuThemeData _mapPopupMenuThemeData(legacy.PopupMenuThemeData t) {
  return modern.PopupMenuThemeData(
    color: t.color,
    shape: t.shape,
    menuPadding: t.menuPadding,
    elevation: t.elevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    textStyle: t.textStyle,
    labelTextStyle: t.labelTextStyle,
    enableFeedback: t.enableFeedback,
    mouseCursor: t.mouseCursor,
    position: t.position == null
        ? null
        : modern.PopupMenuPosition.values[legacy.PopupMenuPosition.values
              .indexOf(t.position!)],
    iconColor: t.iconColor,
    iconSize: t.iconSize,
  );
}

modern.ProgressIndicatorThemeData _mapProgressIndicatorThemeData(
  legacy.ProgressIndicatorThemeData t,
) {
  return modern.ProgressIndicatorThemeData(
    color: t.color,
    linearTrackColor: t.linearTrackColor,
    linearMinHeight: t.linearMinHeight,
    circularTrackColor: t.circularTrackColor,
    refreshBackgroundColor: t.refreshBackgroundColor,
    borderRadius: t.borderRadius,
    stopIndicatorColor: t.stopIndicatorColor,
    stopIndicatorRadius: t.stopIndicatorRadius,
    strokeWidth: t.strokeWidth,
    strokeAlign: t.strokeAlign,
    strokeCap: t.strokeCap,
    constraints: t.constraints,
    trackGap: t.trackGap,
    circularTrackPadding: t.circularTrackPadding,
    controller: t.controller,
  );
}

modern.RadioThemeData _mapRadioThemeData(legacy.RadioThemeData t) {
  return modern.RadioThemeData(
    mouseCursor: t.mouseCursor,
    fillColor: t.fillColor,
    overlayColor: t.overlayColor,
    splashRadius: t.splashRadius,
    materialTapTargetSize: t.materialTapTargetSize == null
        ? null
        : modern.MaterialTapTargetSize.values[legacy
              .MaterialTapTargetSize
              .values
              .indexOf(t.materialTapTargetSize!)],
    visualDensity: t.visualDensity == null
        ? null
        : _mapVisualDensity(t.visualDensity!),
    backgroundColor: t.backgroundColor,
    side: t.side,
    innerRadius: t.innerRadius,
  );
}

modern.SearchBarThemeData _mapSearchBarThemeData(legacy.SearchBarThemeData t) {
  return modern.SearchBarThemeData(
    elevation: t.elevation,
    backgroundColor: t.backgroundColor,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    overlayColor: t.overlayColor,
    side: t.side,
    shape: t.shape,
    padding: t.padding,
    textStyle: t.textStyle,
    hintStyle: t.hintStyle,
    constraints: t.constraints,
    textCapitalization: t.textCapitalization,
  );
}

modern.SearchViewThemeData _mapSearchViewThemeData(
  legacy.SearchViewThemeData t,
) {
  return modern.SearchViewThemeData(
    backgroundColor: t.backgroundColor,
    elevation: t.elevation,
    surfaceTintColor: t.surfaceTintColor,
    constraints: t.constraints,
    padding: t.padding,
    barPadding: t.barPadding,
    shrinkWrap: t.shrinkWrap,
    side: t.side,
    shape: t.shape,
    headerHeight: t.headerHeight,
    headerTextStyle: t.headerTextStyle,
    headerHintStyle: t.headerHintStyle,
    dividerColor: t.dividerColor,
  );
}

modern.SegmentedButtonThemeData _mapSegmentedButtonThemeData(
  legacy.SegmentedButtonThemeData t,
) {
  return modern.SegmentedButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
    selectedIcon: t.selectedIcon,
  );
}

modern.SliderThemeData _mapSliderThemeData(legacy.SliderThemeData t) {
  return modern.SliderThemeData(
    trackHeight: t.trackHeight,
    activeTrackColor: t.activeTrackColor,
    inactiveTrackColor: t.inactiveTrackColor,
    secondaryActiveTrackColor: t.secondaryActiveTrackColor,
    disabledActiveTrackColor: t.disabledActiveTrackColor,
    disabledInactiveTrackColor: t.disabledInactiveTrackColor,
    disabledSecondaryActiveTrackColor: t.disabledSecondaryActiveTrackColor,
    activeTickMarkColor: t.activeTickMarkColor,
    inactiveTickMarkColor: t.inactiveTickMarkColor,
    disabledActiveTickMarkColor: t.disabledActiveTickMarkColor,
    disabledInactiveTickMarkColor: t.disabledInactiveTickMarkColor,
    thumbColor: t.thumbColor,
    overlappingShapeStrokeColor: t.overlappingShapeStrokeColor,
    disabledThumbColor: t.disabledThumbColor,
    overlayColor: t.overlayColor,
    valueIndicatorColor: t.valueIndicatorColor,
    valueIndicatorStrokeColor: t.valueIndicatorStrokeColor,
    valueIndicatorShape: _mapSliderComponentShapeShapes(t.valueIndicatorShape),
    rangeValueIndicatorShape: _mapRangeSliderValueIndicatorShapeShapes(
      t.rangeValueIndicatorShape,
    ),
    showValueIndicator: t.showValueIndicator == null
        ? null
        : modern.ShowValueIndicator.values[legacy.ShowValueIndicator.values
              .indexOf(t.showValueIndicator!)],
    valueIndicatorTextStyle: t.valueIndicatorTextStyle,
    minThumbSeparation: t.minThumbSeparation,
    mouseCursor: t.mouseCursor,
    allowedInteraction: t.allowedInteraction == null
        ? null
        : modern.SliderInteraction.values[legacy.SliderInteraction.values
              .indexOf(t.allowedInteraction!)],
    padding: t.padding,
    thumbSize: t.thumbSize,
    trackGap: t.trackGap,
  );
}

modern.SnackBarThemeData _mapSnackBarThemeData(legacy.SnackBarThemeData t) {
  return modern.SnackBarThemeData(
    backgroundColor: t.backgroundColor,
    actionTextColor: t.actionTextColor,
    disabledActionTextColor: t.disabledActionTextColor,
    contentTextStyle: t.contentTextStyle,
    elevation: t.elevation,
    shape: t.shape,
    behavior: t.behavior == null
        ? null
        : modern.SnackBarBehavior.values[legacy.SnackBarBehavior.values.indexOf(
            t.behavior!,
          )],
    width: t.width,
    insetPadding: t.insetPadding,
    showCloseIcon: t.showCloseIcon,
    closeIconColor: t.closeIconColor,
    actionOverflowThreshold: t.actionOverflowThreshold,
    actionBackgroundColor: t.actionBackgroundColor,
    disabledActionBackgroundColor: t.disabledActionBackgroundColor,
    dismissDirection: t.dismissDirection,
  );
}

modern.SwitchThemeData _mapSwitchThemeData(legacy.SwitchThemeData t) {
  return modern.SwitchThemeData(
    thumbColor: t.thumbColor,
    trackColor: t.trackColor,
    trackOutlineColor: t.trackOutlineColor,
    trackOutlineWidth: t.trackOutlineWidth,
    materialTapTargetSize: t.materialTapTargetSize == null
        ? null
        : modern.MaterialTapTargetSize.values[legacy
              .MaterialTapTargetSize
              .values
              .indexOf(t.materialTapTargetSize!)],
    mouseCursor: t.mouseCursor,
    overlayColor: t.overlayColor,
    splashRadius: t.splashRadius,
    thumbIcon: t.thumbIcon,
    padding: t.padding,
  );
}

modern.TabBarThemeData _mapTabBarThemeData(legacy.TabBarThemeData t) {
  return modern.TabBarThemeData(
    indicator: t.indicator,
    indicatorColor: t.indicatorColor,
    indicatorSize: t.indicatorSize == null
        ? null
        : modern.TabBarIndicatorSize.values[legacy.TabBarIndicatorSize.values
              .indexOf(t.indicatorSize!)],
    dividerColor: t.dividerColor,
    dividerHeight: t.dividerHeight,
    labelColor: t.labelColor,
    labelPadding: t.labelPadding,
    labelStyle: t.labelStyle,
    unselectedLabelColor: t.unselectedLabelColor,
    unselectedLabelStyle: t.unselectedLabelStyle,
    overlayColor: t.overlayColor,
    mouseCursor: t.mouseCursor,
    tabAlignment: t.tabAlignment == null
        ? null
        : modern.TabAlignment.values[legacy.TabAlignment.values.indexOf(
            t.tabAlignment!,
          )],
    textScaler: t.textScaler,
    indicatorAnimation: t.indicatorAnimation == null
        ? null
        : modern.TabIndicatorAnimation.values[legacy
              .TabIndicatorAnimation
              .values
              .indexOf(t.indicatorAnimation!)],
    splashBorderRadius: t.splashBorderRadius,
  );
}

modern.TextButtonThemeData _mapTextButtonThemeData(
  legacy.TextButtonThemeData t,
) {
  return modern.TextButtonThemeData(
    style: t.style == null ? null : _mapButtonStyle(t.style!),
  );
}

modern.TextSelectionThemeData _mapTextSelectionThemeData(
  legacy.TextSelectionThemeData t,
) {
  return modern.TextSelectionThemeData(
    cursorColor: t.cursorColor,
    selectionColor: t.selectionColor,
    selectionHandleColor: t.selectionHandleColor,
  );
}

modern.TimePickerThemeData _mapTimePickerThemeData(
  legacy.TimePickerThemeData t,
) {
  return modern.TimePickerThemeData(
    backgroundColor: t.backgroundColor,
    cancelButtonStyle: t.cancelButtonStyle == null
        ? null
        : _mapButtonStyle(t.cancelButtonStyle!),
    confirmButtonStyle: t.confirmButtonStyle == null
        ? null
        : _mapButtonStyle(t.confirmButtonStyle!),
    dayPeriodBorderSide: t.dayPeriodBorderSide,
    dayPeriodColor: t.dayPeriodColor,
    dayPeriodShape: t.dayPeriodShape,
    dayPeriodTextColor: t.dayPeriodTextColor,
    dayPeriodTextStyle: t.dayPeriodTextStyle,
    dialBackgroundColor: t.dialBackgroundColor,
    dialHandColor: t.dialHandColor,
    dialTextColor: t.dialTextColor,
    dialTextStyle: t.dialTextStyle,
    elevation: t.elevation,
    entryModeIconColor: t.entryModeIconColor,
    helpTextStyle: t.helpTextStyle,
    hourMinuteColor: t.hourMinuteColor,
    hourMinuteShape: t.hourMinuteShape,
    hourMinuteTextColor: t.hourMinuteTextColor,
    hourMinuteTextStyle: t.hourMinuteTextStyle,
    inputDecorationTheme: _mapInputDecorationThemeDataObject(
      t.inputDecorationTheme,
    ),
    padding: t.padding,
    shape: t.shape,
    timeSelectorSeparatorColor: t.timeSelectorSeparatorColor,
    timeSelectorSeparatorTextStyle: t.timeSelectorSeparatorTextStyle,
  );
}

modern.ToggleButtonsThemeData _mapToggleButtonsThemeData(
  legacy.ToggleButtonsThemeData t,
) {
  return modern.ToggleButtonsThemeData(
    textStyle: t.textStyle,
    constraints: t.constraints,
    color: t.color,
    selectedColor: t.selectedColor,
    disabledColor: t.disabledColor,
    fillColor: t.fillColor,
    focusColor: t.focusColor,
    highlightColor: t.highlightColor,
    hoverColor: t.hoverColor,
    splashColor: t.splashColor,
    borderColor: t.borderColor,
    selectedBorderColor: t.selectedBorderColor,
    disabledBorderColor: t.disabledBorderColor,
    borderRadius: t.borderRadius,
    borderWidth: t.borderWidth,
  );
}

modern.TooltipThemeData _mapTooltipThemeData(legacy.TooltipThemeData t) {
  return modern.TooltipThemeData(
    constraints: t.constraints,
    padding: t.padding,
    margin: t.margin,
    verticalOffset: t.verticalOffset,
    preferBelow: t.preferBelow,
    excludeFromSemantics: t.excludeFromSemantics,
    decoration: t.decoration,
    textStyle: t.textStyle,
    textAlign: t.textAlign,
    waitDuration: t.waitDuration,
    showDuration: t.showDuration,
    exitDuration: t.exitDuration,
    triggerMode: t.triggerMode,
    enableFeedback: t.enableFeedback,
  );
}

modern.InputDecorationThemeData _mapInputDecorationThemeData(
  legacy.InputDecorationThemeData t,
) {
  return modern.InputDecorationThemeData(
    labelStyle: t.labelStyle,
    floatingLabelStyle: t.floatingLabelStyle,
    helperStyle: t.helperStyle,
    helperMaxLines: t.helperMaxLines,
    hintStyle: t.hintStyle,
    hintFadeDuration: t.hintFadeDuration,
    hintMaxLines: t.hintMaxLines,
    errorStyle: t.errorStyle,
    errorMaxLines: t.errorMaxLines,
    floatingLabelBehavior:
        modern.FloatingLabelBehavior.values[legacy.FloatingLabelBehavior.values
            .indexOf(t.floatingLabelBehavior)],
    floatingLabelAlignment: _mapFloatingLabelAlignment(
      t.floatingLabelAlignment,
    ),
    isDense: t.isDense,
    contentPadding: t.contentPadding,
    isCollapsed: t.isCollapsed,
    iconColor: t.iconColor,
    prefixStyle: t.prefixStyle,
    prefixIconColor: t.prefixIconColor,
    prefixIconConstraints: t.prefixIconConstraints,
    suffixStyle: t.suffixStyle,
    suffixIconColor: t.suffixIconColor,
    suffixIconConstraints: t.suffixIconConstraints,
    counterStyle: t.counterStyle,
    filled: t.filled,
    fillColor: t.fillColor,
    activeIndicatorBorder: t.activeIndicatorBorder,
    outlineBorder: t.outlineBorder,
    focusColor: t.focusColor,
    hoverColor: t.hoverColor,
    errorBorder: t.errorBorder == null ? null : _mapInputBorder(t.errorBorder!),
    focusedBorder: t.focusedBorder == null
        ? null
        : _mapInputBorder(t.focusedBorder!),
    focusedErrorBorder: t.focusedErrorBorder == null
        ? null
        : _mapInputBorder(t.focusedErrorBorder!),
    disabledBorder: t.disabledBorder == null
        ? null
        : _mapInputBorder(t.disabledBorder!),
    enabledBorder: t.enabledBorder == null
        ? null
        : _mapInputBorder(t.enabledBorder!),
    border: t.border == null ? null : _mapInputBorder(t.border!),
    alignLabelWithHint: t.alignLabelWithHint,
    constraints: t.constraints,
    visualDensity: t.visualDensity == null
        ? null
        : _mapVisualDensity(t.visualDensity!),
  );
}

modern.AppBarThemeData _mapAppBarThemeData(legacy.AppBarThemeData t) {
  return modern.AppBarThemeData(
    backgroundColor: t.backgroundColor,
    foregroundColor: t.foregroundColor,
    elevation: t.elevation,
    scrolledUnderElevation: t.scrolledUnderElevation,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    shape: t.shape,
    iconTheme: t.iconTheme,
    actionsIconTheme: t.actionsIconTheme,
    centerTitle: t.centerTitle,
    titleSpacing: t.titleSpacing,
    leadingWidth: t.leadingWidth,
    toolbarHeight: t.toolbarHeight,
    toolbarTextStyle: t.toolbarTextStyle,
    titleTextStyle: t.titleTextStyle,
    actionsPadding: t.actionsPadding,
  );
}

modern.VisualDensity _mapVisualDensity(legacy.VisualDensity t) {
  return modern.VisualDensity(horizontal: t.horizontal, vertical: t.vertical);
}

modern.ButtonStyle _mapButtonStyle(legacy.ButtonStyle t) {
  return modern.ButtonStyle(
    textStyle: t.textStyle,
    backgroundColor: t.backgroundColor,
    foregroundColor: t.foregroundColor,
    overlayColor: t.overlayColor,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    elevation: t.elevation,
    padding: t.padding,
    minimumSize: t.minimumSize,
    fixedSize: t.fixedSize,
    maximumSize: t.maximumSize,
    iconColor: t.iconColor,
    iconSize: t.iconSize,
    iconAlignment: t.iconAlignment == null
        ? null
        : modern.IconAlignment.values[legacy.IconAlignment.values.indexOf(
            t.iconAlignment!,
          )],
    side: t.side,
    shape: t.shape,
    mouseCursor: t.mouseCursor,
    visualDensity: t.visualDensity == null
        ? null
        : _mapVisualDensity(t.visualDensity!),
    tapTargetSize: t.tapTargetSize == null
        ? null
        : modern.MaterialTapTargetSize.values[legacy
              .MaterialTapTargetSize
              .values
              .indexOf(t.tapTargetSize!)],
    animationDuration: t.animationDuration,
    enableFeedback: t.enableFeedback,
    alignment: t.alignment,
    backgroundBuilder: t.backgroundBuilder,
    foregroundBuilder: t.foregroundBuilder,
  );
}

modern.MenuStyle _mapMenuStyle(legacy.MenuStyle t) {
  return modern.MenuStyle(
    backgroundColor: t.backgroundColor,
    shadowColor: t.shadowColor,
    surfaceTintColor: t.surfaceTintColor,
    elevation: t.elevation,
    padding: t.padding,
    minimumSize: t.minimumSize,
    fixedSize: t.fixedSize,
    maximumSize: t.maximumSize,
    side: t.side,
    shape: t.shape,
    mouseCursor: t.mouseCursor,
    visualDensity: t.visualDensity == null
        ? null
        : _mapVisualDensity(t.visualDensity!),
    alignment: t.alignment,
  );
}

/// Converts a legacy flex_color_scheme `ThemeData` into a modern material_ui `ThemeData`.
// ignore: deprecated_member_use
modern.ThemeData flexThemeToModern(legacy.ThemeData t) {
  return modern.ThemeData(
    applyElevationOverlayColor: t.applyElevationOverlayColor,
    inputDecorationTheme: _mapInputDecorationThemeDataObject(
      t.inputDecorationTheme,
    ),
    materialTapTargetSize:
        modern.MaterialTapTargetSize.values[legacy.MaterialTapTargetSize.values
            .indexOf(t.materialTapTargetSize)],
    pageTransitionsTheme: _mapPageTransitionsTheme(t.pageTransitionsTheme),
    platform: t.platform,
    scrollbarTheme: _mapScrollbarThemeData(t.scrollbarTheme),
    // `splashFactory` is a factory closure, never a NoSplash instance,
    // so detect the legacy const factory by identity.
    splashFactory: identical(t.splashFactory, legacy.NoSplash.splashFactory)
        ? modern.NoSplash.splashFactory
        : null,
    useMaterial3: t.useMaterial3,
    visualDensity: modern.VisualDensity(
      horizontal: t.visualDensity.horizontal,
      vertical: t.visualDensity.vertical,
    ),
    colorScheme: _mapColorScheme(t.colorScheme),
    brightness: t.brightness,
    cardColor: t.cardColor,
    disabledColor: t.disabledColor,
    dividerColor: t.dividerColor,
    focusColor: t.focusColor,
    highlightColor: t.highlightColor,
    hintColor: t.hintColor,
    hoverColor: t.hoverColor,
    primaryColor: t.primaryColor,
    primaryColorDark: t.primaryColorDark,
    primaryColorLight: t.primaryColorLight,
    scaffoldBackgroundColor: t.scaffoldBackgroundColor,
    secondaryHeaderColor: t.secondaryHeaderColor,
    shadowColor: t.shadowColor,
    splashColor: t.splashColor,
    unselectedWidgetColor: t.unselectedWidgetColor,
    iconTheme: t.iconTheme,
    primaryIconTheme: t.primaryIconTheme,
    primaryTextTheme: _mapTextTheme(t.primaryTextTheme),
    textTheme: _mapTextTheme(t.textTheme),
    typography: _mapTypography(t.typography),
    actionIconTheme: t.actionIconTheme == null
        ? null
        : _mapActionIconThemeData(t.actionIconTheme!),
    appBarTheme: _mapAppBarThemeDataObject(t.appBarTheme),
    badgeTheme: _mapBadgeThemeData(t.badgeTheme),
    bannerTheme: _mapMaterialBannerThemeData(t.bannerTheme),
    bottomAppBarTheme: _mapBottomAppBarThemeData(t.bottomAppBarTheme),
    bottomNavigationBarTheme: _mapBottomNavigationBarThemeData(
      t.bottomNavigationBarTheme,
    ),
    bottomSheetTheme: _mapBottomSheetThemeData(t.bottomSheetTheme),
    buttonTheme: _mapButtonThemeData(t.buttonTheme),
    cardTheme: _mapCardThemeData(t.cardTheme),
    carouselViewTheme: _mapCarouselViewThemeData(t.carouselViewTheme),
    checkboxTheme: _mapCheckboxThemeData(t.checkboxTheme),
    chipTheme: _mapChipThemeData(t.chipTheme),
    dataTableTheme: _mapDataTableThemeData(t.dataTableTheme),
    datePickerTheme: _mapDatePickerThemeData(t.datePickerTheme),
    dialogTheme: _mapDialogThemeData(t.dialogTheme),
    dividerTheme: _mapDividerThemeData(t.dividerTheme),
    drawerTheme: _mapDrawerThemeData(t.drawerTheme),
    dropdownMenuTheme: _mapDropdownMenuThemeData(t.dropdownMenuTheme),
    elevatedButtonTheme: _mapElevatedButtonThemeData(t.elevatedButtonTheme),
    expansionTileTheme: _mapExpansionTileThemeData(t.expansionTileTheme),
    filledButtonTheme: _mapFilledButtonThemeData(t.filledButtonTheme),
    floatingActionButtonTheme: _mapFloatingActionButtonThemeData(
      t.floatingActionButtonTheme,
    ),
    iconButtonTheme: _mapIconButtonThemeData(t.iconButtonTheme),
    listTileTheme: _mapListTileThemeData(t.listTileTheme),
    menuBarTheme: _mapMenuBarThemeData(t.menuBarTheme),
    menuButtonTheme: _mapMenuButtonThemeData(t.menuButtonTheme),
    menuTheme: _mapMenuThemeData(t.menuTheme),
    navigationBarTheme: _mapNavigationBarThemeData(t.navigationBarTheme),
    navigationDrawerTheme: _mapNavigationDrawerThemeData(
      t.navigationDrawerTheme,
    ),
    navigationRailTheme: _mapNavigationRailThemeData(t.navigationRailTheme),
    outlinedButtonTheme: _mapOutlinedButtonThemeData(t.outlinedButtonTheme),
    popupMenuTheme: _mapPopupMenuThemeData(t.popupMenuTheme),
    progressIndicatorTheme: _mapProgressIndicatorThemeData(
      t.progressIndicatorTheme,
    ),
    radioTheme: _mapRadioThemeData(t.radioTheme),
    searchBarTheme: _mapSearchBarThemeData(t.searchBarTheme),
    searchViewTheme: _mapSearchViewThemeData(t.searchViewTheme),
    segmentedButtonTheme: _mapSegmentedButtonThemeData(t.segmentedButtonTheme),
    sliderTheme: _mapSliderThemeData(t.sliderTheme),
    snackBarTheme: _mapSnackBarThemeData(t.snackBarTheme),
    switchTheme: _mapSwitchThemeData(t.switchTheme),
    tabBarTheme: _mapTabBarThemeData(t.tabBarTheme),
    textButtonTheme: _mapTextButtonThemeData(t.textButtonTheme),
    textSelectionTheme: _mapTextSelectionThemeData(t.textSelectionTheme),
    timePickerTheme: _mapTimePickerThemeData(t.timePickerTheme),
    toggleButtonsTheme: _mapToggleButtonsThemeData(t.toggleButtonsTheme),
    tooltipTheme: _mapTooltipThemeData(t.tooltipTheme),
  );
}

// Fields intentionally not mapped (null in FlexColorScheme output or unmappable):
//   ThemeData.useSystemColors (not public), ThemeData.colorSchemeSeed (not public), ThemeData.primarySwatch (not public), ThemeData.fontFamily (not public), ThemeData.fontFamilyFallback (not public), ThemeData.package (not public)
