// Mocks generated by Mockito 5.4.6 from annotations
// in kafkalyzer/test/src/rust/api/rust_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ffi' as _i5;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart'
    as _i4;
import 'package:kafkalyzer/src/rust/api/kafka_consumer.dart' as _i8;
import 'package:kafkalyzer/src/rust/api/kafka_metadata.dart' as _i10;
import 'package:kafkalyzer/src/rust/api/kafka_types.dart' as _i9;
import 'package:kafkalyzer/src/rust/api/kafka_utils.dart' as _i2;
import 'package:kafkalyzer/src/rust/frb_generated.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClientConfig_0 extends _i1.SmartFake implements _i2.ClientConfig {
  _FakeClientConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RustLibApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRustLibApi extends _i1.Mock implements _i3.RustLibApi {
  MockRustLibApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClientConfig =>
      (super.noSuchMethod(
            Invocation.getter(#rust_arc_increment_strong_count_ClientConfig),
            returnValue: (_i5.Pointer<_i5.Void> __p0) {},
          )
          as _i4.RustArcIncrementStrongCountFnType);

  @override
  _i4.RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClientConfig =>
      (super.noSuchMethod(
            Invocation.getter(#rust_arc_decrement_strong_count_ClientConfig),
            returnValue: (_i5.Pointer<_i5.Void> __p0) {},
          )
          as _i4.RustArcDecrementStrongCountFnType);

  @override
  _i5.Pointer<_i5.NativeFunction<_i5.Void Function(_i5.Pointer<_i5.Void>)>>
  get rust_arc_decrement_strong_count_ClientConfigPtr =>
      (super.noSuchMethod(
            Invocation.getter(#rust_arc_decrement_strong_count_ClientConfigPtr),
            returnValue: _i6
                .dummyValue<
                  _i5.Pointer<
                    _i5.NativeFunction<_i5.Void Function(_i5.Pointer<_i5.Void>)>
                  >
                >(
                  this,
                  Invocation.getter(
                    #rust_arc_decrement_strong_count_ClientConfigPtr,
                  ),
                ),
          )
          as _i5.Pointer<
            _i5.NativeFunction<_i5.Void Function(_i5.Pointer<_i5.Void>)>
          >);

  @override
  _i7.Stream<_i8.KafkaMessage> crateApiKafkaConsumerConsumeWithFilter({
    required _i9.ClusterProfile? profile,
    required String? topic,
    List<String>? filterTerms,
    String? filterField,
    required _i9.FilterType? filterType,
    required _i9.SearchScope? searchScope,
    int? startOffset,
    int? startTimestamp,
    int? startPartition,
    String? fastTraceKey,
    int? endOffset,
    int? endTimestamp,
    int? maxResults,
    required bool? runForever,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiKafkaConsumerConsumeWithFilter, [], {
              #profile: profile,
              #topic: topic,
              #filterTerms: filterTerms,
              #filterField: filterField,
              #filterType: filterType,
              #searchScope: searchScope,
              #startOffset: startOffset,
              #startTimestamp: startTimestamp,
              #startPartition: startPartition,
              #fastTraceKey: fastTraceKey,
              #endOffset: endOffset,
              #endTimestamp: endTimestamp,
              #maxResults: maxResults,
              #runForever: runForever,
            }),
            returnValue: _i7.Stream<_i8.KafkaMessage>.empty(),
          )
          as _i7.Stream<_i8.KafkaMessage>);

  @override
  _i7.Future<_i2.ClientConfig> crateApiKafkaUtilsCreateConfig({
    required _i9.ClusterProfile? profile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiKafkaUtilsCreateConfig, [], {
              #profile: profile,
            }),
            returnValue: _i7.Future<_i2.ClientConfig>.value(
              _FakeClientConfig_0(
                this,
                Invocation.method(#crateApiKafkaUtilsCreateConfig, [], {
                  #profile: profile,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ClientConfig>);

  @override
  _i7.Future<String> crateApiSchemaRegistryFetchSchema({
    required _i9.ClusterProfile? profile,
    required String? subject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiSchemaRegistryFetchSchema, [], {
              #profile: profile,
              #subject: subject,
            }),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#crateApiSchemaRegistryFetchSchema, [], {
                  #profile: profile,
                  #subject: subject,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<String>> crateApiSchemaRegistryFetchSubjects({
    required _i9.ClusterProfile? profile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiSchemaRegistryFetchSubjects, [], {
              #profile: profile,
            }),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i10.TopicMetadata>> crateApiKafkaMetadataFetchTopics({
    required _i9.ClusterProfile? profile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiKafkaMetadataFetchTopics, [], {
              #profile: profile,
            }),
            returnValue: _i7.Future<List<_i10.TopicMetadata>>.value(
              <_i10.TopicMetadata>[],
            ),
          )
          as _i7.Future<List<_i10.TopicMetadata>>);

  @override
  _i7.Future<void> crateApiInitApp() =>
      (super.noSuchMethod(
            Invocation.method(#crateApiInitApp, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> crateApiKafkaUtilsMurmur2({required List<int>? data}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiKafkaUtilsMurmur2, [], {#data: data}),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> crateApiKafkaUtilsToPositive({required int? number}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiKafkaUtilsToPositive, [], {
              #number: number,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<bool> crateApiKafkaMetadataValidateConnection({
    required _i9.ClusterProfile? profile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiKafkaMetadataValidateConnection, [], {
              #profile: profile,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
