// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_domain`, `to_domain`, `to_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

class ClusterProfile {
  final String name;
  final String bootstrapServers;
  final String? saslUsername;
  final String? saslPassword;
  final String? mechanism;
  final String? securityProtocol;
  final String? schemaRegistryUrl;
  final String? sslKeystoreLocation;
  final String? sslKeystorePassword;
  final String? sslTruststoreLocation;
  final String? sslTruststorePassword;

  const ClusterProfile({
    required this.name,
    required this.bootstrapServers,
    this.saslUsername,
    this.saslPassword,
    this.mechanism,
    this.securityProtocol,
    this.schemaRegistryUrl,
    this.sslKeystoreLocation,
    this.sslKeystorePassword,
    this.sslTruststoreLocation,
    this.sslTruststorePassword,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      bootstrapServers.hashCode ^
      saslUsername.hashCode ^
      saslPassword.hashCode ^
      mechanism.hashCode ^
      securityProtocol.hashCode ^
      schemaRegistryUrl.hashCode ^
      sslKeystoreLocation.hashCode ^
      sslKeystorePassword.hashCode ^
      sslTruststoreLocation.hashCode ^
      sslTruststorePassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClusterProfile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bootstrapServers == other.bootstrapServers &&
          saslUsername == other.saslUsername &&
          saslPassword == other.saslPassword &&
          mechanism == other.mechanism &&
          securityProtocol == other.securityProtocol &&
          schemaRegistryUrl == other.schemaRegistryUrl &&
          sslKeystoreLocation == other.sslKeystoreLocation &&
          sslKeystorePassword == other.sslKeystorePassword &&
          sslTruststoreLocation == other.sslTruststoreLocation &&
          sslTruststorePassword == other.sslTruststorePassword;
}

enum FilterType { contains, regex, exact }

enum SearchScope { key, value, both }
