// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'kafka_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<TopicAnalysisProgress> analyzeTopicContent({
  required ClusterProfile profile,
  required String topic,
  PlatformInt64? maxMessages,
  required bool sampleFromLatest,
}) => KafkalyzerRustLib.instance.api.crateApiKafkaAnalyzerAnalyzeTopicContent(
  profile: profile,
  topic: topic,
  maxMessages: maxMessages,
  sampleFromLatest: sampleFromLatest,
);
