// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'kafka_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<bool> validateConnection({required ClusterProfile profile}) => RustLib
    .instance
    .api
    .crateApiKafkaMetadataValidateConnection(profile: profile);

Future<List<TopicMetadata>> fetchTopics({required ClusterProfile profile}) =>
    RustLib.instance.api.crateApiKafkaMetadataFetchTopics(profile: profile);

class TopicMetadata {
  final String name;
  final int partitionCount;
  final int replicationFactor;
  final String? cleanupPolicy;
  final String? retentionMs;

  const TopicMetadata({
    required this.name,
    required this.partitionCount,
    required this.replicationFactor,
    this.cleanupPolicy,
    this.retentionMs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      partitionCount.hashCode ^
      replicationFactor.hashCode ^
      cleanupPolicy.hashCode ^
      retentionMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopicMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          partitionCount == other.partitionCount &&
          replicationFactor == other.replicationFactor &&
          cleanupPolicy == other.cleanupPolicy &&
          retentionMs == other.retentionMs;
}
