// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_domain`, `to_domain`, `to_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

class ClusterProfile {
  final String name;
  final String bootstrapServers;
  final String? saslUsername;
  final String? saslPassword;
  final String? mechanism;
  final String? securityProtocol;
  final String? schemaRegistryUrl;
  final String? sslKeystoreLocation;
  final String? sslKeystorePassword;
  final String? sslTruststoreLocation;
  final String? sslTruststorePassword;
  final String? schemaRegistryUsername;
  final String? schemaRegistryPassword;
  final String? saslKerberosServiceName;
  final String? saslKerberosKeytab;
  final String? saslKerberosPrincipal;
  final String? saslKerberosConf;
  final String? saslOauthbearerToken;
  final String? sslPemCertificateLocation;
  final String? sslPemKeyLocation;
  final String? sslPemKeyPassword;

  const ClusterProfile({
    required this.name,
    required this.bootstrapServers,
    this.saslUsername,
    this.saslPassword,
    this.mechanism,
    this.securityProtocol,
    this.schemaRegistryUrl,
    this.sslKeystoreLocation,
    this.sslKeystorePassword,
    this.sslTruststoreLocation,
    this.sslTruststorePassword,
    this.schemaRegistryUsername,
    this.schemaRegistryPassword,
    this.saslKerberosServiceName,
    this.saslKerberosKeytab,
    this.saslKerberosPrincipal,
    this.saslKerberosConf,
    this.saslOauthbearerToken,
    this.sslPemCertificateLocation,
    this.sslPemKeyLocation,
    this.sslPemKeyPassword,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      bootstrapServers.hashCode ^
      saslUsername.hashCode ^
      saslPassword.hashCode ^
      mechanism.hashCode ^
      securityProtocol.hashCode ^
      schemaRegistryUrl.hashCode ^
      sslKeystoreLocation.hashCode ^
      sslKeystorePassword.hashCode ^
      sslTruststoreLocation.hashCode ^
      sslTruststorePassword.hashCode ^
      schemaRegistryUsername.hashCode ^
      schemaRegistryPassword.hashCode ^
      saslKerberosServiceName.hashCode ^
      saslKerberosKeytab.hashCode ^
      saslKerberosPrincipal.hashCode ^
      saslKerberosConf.hashCode ^
      saslOauthbearerToken.hashCode ^
      sslPemCertificateLocation.hashCode ^
      sslPemKeyLocation.hashCode ^
      sslPemKeyPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClusterProfile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bootstrapServers == other.bootstrapServers &&
          saslUsername == other.saslUsername &&
          saslPassword == other.saslPassword &&
          mechanism == other.mechanism &&
          securityProtocol == other.securityProtocol &&
          schemaRegistryUrl == other.schemaRegistryUrl &&
          sslKeystoreLocation == other.sslKeystoreLocation &&
          sslKeystorePassword == other.sslKeystorePassword &&
          sslTruststoreLocation == other.sslTruststoreLocation &&
          sslTruststorePassword == other.sslTruststorePassword &&
          schemaRegistryUsername == other.schemaRegistryUsername &&
          schemaRegistryPassword == other.schemaRegistryPassword &&
          saslKerberosServiceName == other.saslKerberosServiceName &&
          saslKerberosKeytab == other.saslKerberosKeytab &&
          saslKerberosPrincipal == other.saslKerberosPrincipal &&
          saslKerberosConf == other.saslKerberosConf &&
          saslOauthbearerToken == other.saslOauthbearerToken &&
          sslPemCertificateLocation == other.sslPemCertificateLocation &&
          sslPemKeyLocation == other.sslPemKeyLocation &&
          sslPemKeyPassword == other.sslPemKeyPassword;
}

class ConsumerGroupLag {
  final String groupId;
  final String state;
  final String protocolType;
  final List<TopicPartitionLag> partitionLags;
  final int membersCount;
  final int topicsCount;

  const ConsumerGroupLag({
    required this.groupId,
    required this.state,
    required this.protocolType,
    required this.partitionLags,
    required this.membersCount,
    required this.topicsCount,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      state.hashCode ^
      protocolType.hashCode ^
      partitionLags.hashCode ^
      membersCount.hashCode ^
      topicsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConsumerGroupLag &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          state == other.state &&
          protocolType == other.protocolType &&
          partitionLags == other.partitionLags &&
          membersCount == other.membersCount &&
          topicsCount == other.topicsCount;
}

enum FilterType { contains, regex, exact }

enum SearchScope { key, value, both }

class TopicPartitionLag {
  final String topic;
  final int partition;
  final PlatformInt64 logEndOffset;
  final PlatformInt64 currentOffset;
  final PlatformInt64 lag;

  const TopicPartitionLag({
    required this.topic,
    required this.partition,
    required this.logEndOffset,
    required this.currentOffset,
    required this.lag,
  });

  @override
  int get hashCode =>
      topic.hashCode ^
      partition.hashCode ^
      logEndOffset.hashCode ^
      currentOffset.hashCode ^
      lag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopicPartitionLag &&
          runtimeType == other.runtimeType &&
          topic == other.topic &&
          partition == other.partition &&
          logEndOffset == other.logEndOffset &&
          currentOffset == other.currentOffset &&
          lag == other.lag;
}
