// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'kafka_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

Stream<KafkaMessage> consumeWithFilter({
  required ClusterProfile profile,
  required String topic,
  List<String>? filterTerms,
  String? filterField,
  required FilterType filterType,
  required SearchScope searchScope,
  PlatformInt64? startOffset,
  PlatformInt64? startTimestamp,
  int? startPartition,
  String? fastTraceKey,
  PlatformInt64? endOffset,
  PlatformInt64? endTimestamp,
  int? maxResults,
  required bool runForever,
}) => RustLib.instance.api.crateApiKafkaConsumerConsumeWithFilter(
  profile: profile,
  topic: topic,
  filterTerms: filterTerms,
  filterField: filterField,
  filterType: filterType,
  searchScope: searchScope,
  startOffset: startOffset,
  startTimestamp: startTimestamp,
  startPartition: startPartition,
  fastTraceKey: fastTraceKey,
  endOffset: endOffset,
  endTimestamp: endTimestamp,
  maxResults: maxResults,
  runForever: runForever,
);

class KafkaHeader {
  final String key;
  final String value;

  const KafkaHeader({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KafkaHeader &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class KafkaMessage {
  final String topic;
  final int partition;
  final PlatformInt64 offset;
  final String? key;
  final String? payload;
  final PlatformInt64 timestamp;
  final List<KafkaHeader>? headers;

  const KafkaMessage({
    required this.topic,
    required this.partition,
    required this.offset,
    this.key,
    this.payload,
    required this.timestamp,
    this.headers,
  });

  @override
  int get hashCode =>
      topic.hashCode ^
      partition.hashCode ^
      offset.hashCode ^
      key.hashCode ^
      payload.hashCode ^
      timestamp.hashCode ^
      headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KafkaMessage &&
          runtimeType == other.runtimeType &&
          topic == other.topic &&
          partition == other.partition &&
          offset == other.offset &&
          key == other.key &&
          payload == other.payload &&
          timestamp == other.timestamp &&
          headers == other.headers;
}
